### ISSUE TITLE
Equation numbering

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/nasa-apt#430]
Equations should follow a numbering scheme in order to be reference-able: 
```
e = mc^2            (1)
y = mx + b          (2)
```

Latex has 2 different environments for displaying equations: `math` and `equations`. The former is the default used by `pyLatex`, the library we are using to generate the latex documents and is not numbered, by default. The `equations` environment [does number equations](https://tex.stackexchange.com/questions/75764/how-do-you-make-numbered-equations-in-latex), but is not included by default in `pyLatex`. 

The solution is to use an escape hatch in `pyLatex` and [create a custom environment](https://github.com/JelteF/PyLaTeX/issues/284)

**Comment by wrynearson** [comment]
Implemented with a different approach
