### ISSUE TITLE
Epic: ESDIS Deployment (NGAP)

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#446]
Development of Plans for ESDIS Deployment
Includes support of the transition to ESDIS, Security fixes flagged by ESDIS, and the migration of data.

Includes the following steps / tasks

- [ ] #535 
- [ ]

**Comment by wrynearson** [comment]
Duplicate of https://github.com/NASA-IMPACT/nasa-apt/issues/536
