### ISSUE TITLE
Not Allowing Simultaneous Editing

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#454]

**Comment by oliverroick** [comment]
Potential library to enable simultaneous editing: https://replicache.dev/

**Comment by aboydnw** [comment]
@oliverroick I've been trying to think of how this could work. It seems like either a) we fully enable simultaneous editing with google-drive-like functionality to allow users to see who is in a report editing at the same time or b) only allow one user to edit a report at a time. 

The first one feels like opening a can of worms (unless there is a library like the one above to do it)

For the second one, it seems like some action should "lock" the form and some action should "unlock" the form. 
Actions to lock the form:
- Clicking Edit from the ellipses in the top left of the View Report page
- Clicking Editing from the dropdown in the breadcrumbs of the View Report page

Potential actions to unlock the form:
- Clicking View from the breadcrumbs of the Edit Report page
- Closing the tab or window
- Not making any changes to the form for 30 minutes (maybe we should throw up a modal saying their session expired and drop them on the View report page, maybe this could be a new ticket if it's something we want to do)

What do you think?

**Comment by oliverroick** [comment]
I looked into Replicache and I think it isn't an option. Setting up Replicache and integrating it with the existing front-end architecture will take several weeks and will certainly not be finished for the June deadline. 

--- 

Thinking about the implementation side of this, we need to consider the following:

- When a user try to open a document form, the front-end checks with the backend if the report is locked.
	- If the report is locked, the server responds with an error message. The user is sent to the document detail page and shown a message saying the document is locked.
	- If the report is not locked, the server sends a success message and updates the database indicating that the report is locked. We need to store the timestamp and username so we can later verify that updates are being sent from the user who locked the form. The user is sent to the document form.
- A lock is limited to 30 minutes.
- To update a form, in the backend we need to check if the current updating user has locked the form and if the lock has expired. 
	- If the user has locked and the lock is still active, we update the form, reset the lock timestamp, and return a success response.
	- Otherwise, we return an error response.
- In the frontend, we track when the lock was set. We show a popup prompting the user to refresh the lock five minutes before the lock is set to expire. 
	- If the user refreshes the lock, we send a request to the backend. The backend checks if the requesting user has locked the form and if the lock has expired. 
		- If the user has locked and the lock is still active, we reset the lock timestamp, and return a success response.
		- Otherwise, we return an error response.
	- If the user does not refresh the lock, we redirect the user to the report page. **What happens to unsaved changes?**
- Users can unlock a report by closing the form, either by navigating to a different page, or by closing the browser tab.
	- To unlock the form, we send a request to the backend. If the requesting user has locked the form, we reset the lock user and timestamp. 

This is a lot of work, I'd say this takes at least a sprint for one person to implement properly.

**Comment by aboydnw** [comment]
Proposed solution for us to move forward with:

Lock down the document when a user edits the ATBD. However, give other contributors for the document the power to take over edit capabilities when another user is already in the document. Any information originally put in the document would be lost, so we would use a warning modal for the second user.

## AC:
1. Given User A is on the ATBD Editing page, when User B tries to access the ATBD Editing page for that same ATBD (via the Edit button from the top right ellipses or the Editing dropdown in top left) then User B is presented with a warning modal (content described below) and can cancel the action or take over edit access
2. Given User A is on the ATBD Editing page, when User B takes over ownership for that same ATBD (via modal from AC 1) then User A sees a modal describing that User B took access (content described below) and can return to the ATBD View page
3. Given there are no users currently in the ATBD Editing page for an ATBD, when any user tries to access that ATBD Editing page, they are able to do so unimpeded

## Modal Content

User Warning Modal When Attempting to Edit

Header: 
"Overwrite Other Changes?"

Description:
"<User A name> is currently editing this document. If you continue, you will overwrite any changes they have made.

We suggest verifying with <User A> before continuing."

Actions:
Primary action: Continue & Overwrite
Secondary (tertiary?) action: Cancel

User Alert that Somebody Took Over Control

Header:
"Another User Took Over Editing"

Description:
"<User B name> recently took over control of editing this document. Any unsaved changes can be recovered for a short period of time by asking <User B> to exit the Editing page. This will allow you to Edit this document again and recover your changes.

We suggest reaching out to <User B> immediately if you need to save your changes."

Actions
Primary action: Return to ATBD

**Comment by aboydnw** [comment]
@oliverroick let me know what you think of the AC above

Also, a question came up from IMPACT on this solution. Would it be possible to lock down sections of the report, as opposed to the entire report itself? We'd only want to do it this way if it was a negligible difference in level of effort, but wanted to put it out there as an option. By "sections" I mean the larger sections in each of this dropdown.

![Image](https://user-images.githubusercontent.com/92742765/173413359-3b41bea4-601c-4993-b64a-8bccc82c54dd.png)

**Comment by oliverroick** [comment]
> User Alert that Somebody Took Over Control

This one is going to add some level of effort. We don't have the infrastructure in place to send push notifications to users at the moment. We'd have to set up a web socket to get this done, which is possible but will take some effort (and we need to find out if we will be able to do that under GPC policies)

> Would it be possible to lock down sections of the report, as opposed to the entire report itself? 

Technically it is possible. But it will add some complexity to the workload. Locking the whole ATBD version, we can leverage the existing permissions framework and know it will work. If we want to l lock individual sections, we need to do some design work upfront to figure out to best store lock information (we have to store the locking user per section per version per document), and we have nowhere to put this information at them moment. (As opposed to storing the locking user per version, in this we can "just" add a field to the version table.
