### ISSUE TITLE
Low Priority PDF Styling tweaks

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#461]
https://github.com/NASA-IMPACT/nasa-apt/issues/458
https://github.com/NASA-IMPACT/nasa-apt/issues/459
https://github.com/NASA-IMPACT/nasa-apt/issues/460

**Comment by leothomas** [comment]
Addressed in release [v2.4.0-beta](https://github.com/NASA-IMPACT/nasa-apt/releases/tag/v2.4.0-beta)

**Comment by aboydnw** [comment]
Closing based on comment above.
