### ISSUE TITLE
Journal PDF should only be accessible to document contributors

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/nasa-apt#468]
- [ ] Block access to public users
- [ ] Block access to non document contributors

Curators can access the journal PDF for any document

**Comment by jo-tham** [comment]
backend: I'm assuming this only requires an update of `api/v2/pdf.py` to include `principals` in its args and to user `filter_report_versions` with said principals. also test locally and write a test: ~2 hours

**Comment by aboydnw** [comment]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/92742765/159290635-4621758c-bc61-4ce3-a354-ac9f1efddef9.png">

**Comment by aboydnw** [comment]
@deborahUAH just to confirm on this ticket, should we be blocking access to non document contributors or should anybody logged into the system be able to access the journal pdf?

**Comment by aboydnw** [comment]
@oliverroick can confirm this functionality should be available to any contributors on the document (reviewers, authors, etc)

**Comment by deborahUAH** [comment]
The only people who should be able to access the journal PDF are the ATBD authors, reviewers and the curator.
