### ISSUE TITLE
PDF Generation Errors

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#471]
The goal is to provide more descriptive error messages so the users know what went wrong.

AC:
1. When a PDF fails because it is missing information, alert the user that information is missing (bonus: alert to which information specifically is missing)
2. When a PDF fails for another reason, like service is down or other technical reason, tell the user to refresh and try again
3. Adjust Latex error page so that instead of saying "Here is the LaTex PDF compiler output, if you're a geek:" to say "See below for the LaTex PDF compiler output."

**Comment by leothomas** [comment]
> 1. When a PDF fails because it is missing information, alert the user that information is missing (bonus: alert to which information specifically is missing)

This is not difficult, but requires going over the PDF generation code closely to separate out: 
- Fields which will cause the Latex generation to fail if they're not present (eg: title) 
- Fields which are mandatory for either the journal or regular pdf, but should not cause the Latex generation to fail (eg: if journal pdf generation should error our if `keypoints` is missing, but not regular pdf)
- Non-mandatory fields  

This brings up another question: are users expecting to be able to generate intermediate, or unfinished PDF's? If so we'll need to think about which fields we allow to be blank (eg: intro can be empty, but not title). This will allow users to generate documents which are invalid by AGU's standards. Do we consider it's their responsibility to make sure all necessary fields are there? Should we use placeholders instead? 

> 2. When a PDF fails for another reason, like service is down or other technical reason, tell the user to refresh and try again

This should be relatively easy with a few more Try/Catches in `api/v2/pdf.py`


> 3. Adjust Latex error page so that instead of saying "Here is the LaTex PDF compiler output, if you're a geek:" to say "See below for the LaTex PDF compiler output."

This is really easy. Additionally I would like to parse the LaTex PDF compiler output to filter out a lot of unnecessary information 

For all of the above, including reviewing and re-designing what we consider mandatory/optional fields, I would say 1 sprint

**Comment by aboydnw** [comment]
@leothomas for the first two bullets...

- Much better. I would remove the "We're sorry, it looks like" in the header so it starts with "We weren't"
-  I like collapsing the full output, I think it is useful. I'll let others comment on whether it's intuitive, I sense it might be "intuitive enough" for what this screen is

**Comment by danielfdsilva** [comment]
@leothomas Created a styled template of this page to make it more in line with APT.
I pushed to the `feature/update-pdf-error-text` in a file called `pdf-error.html`. The file is quite long because it includes the logo svg. I'd suggest we use some sort of templating language to populate it (like mustache). All the places that need values are indicated with `{{description}}`.

This is how it looks
![Screen Shot 2022-03-25 at 13 35 02](https://user-images.githubusercontent.com/1090606/160130791-7f8c328c-5ef8-4210-b7d7-6fc95f9f533f.png)
