### ISSUE TITLE
User Guide Updates In App

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#472]
### Feedback from NASA testers

1. The nav title of "Help" was not descriptive enough. "User Guide" would be better
2. Since the user guides are so long, it can be easy to get lost in the user guide.
3. After finding the information they need, users have to scroll all the way back to the top to navigate somewhere else. This is time consuming.

### Acceptance Criteria

- [x] The nav element and page header should say "User Guide"
- [x] The sub-page nave element that currently says "User Guide" should say "APT" 
- [x] Users are able to quickly navigate to different sections of the user guide (i.e. accordion, floating table of contents, or some other solution)
- [x] Once users have found their information, users are able to quickly navigate to somewhere else in the app
- [x] Updated text in [this document](https://docs.google.com/document/d/1cePfusnaVvuGL1WbzflkaOPVFKi2-W_HOFqgseiyZHA/edit?usp=sharing) is shown in the APT user guide
- [x] "Documents" nav element (for users not logged in) should instead say "ATBDs"

**Comment by aboydnw** [comment]
From the conversation today, one option would be to use the sidebar table of contents in the ATBD view page. (screenshot below)
![image](https://user-images.githubusercontent.com/92742765/157793976-7fac3a00-12ec-4453-a90f-9bb82a8270c3.png)

According to Daniel, this might be quite a bit of work, especially considering the User Guide is currently just a markdown file which is not conducive to this table of contents feature. We could explore other options here that are lower level of effort. If I had to prioritize the user navigation actions on this page, here would be my first guess:

1. Being able to navigate away from the user guide (aka go to other pages available to them)
2. Being able to easily find/navigate to a specific section in the user guide

@deborahUAH can you take a look at this ticket and my comment here and provide any feedback?

**Comment by oliverroick** [comment]
> Once users have found their information, users are able to quickly navigate to somewhere else in the app

This is vague. What is the expectation? Should there be links from the help page to the relevant part of the app, ie. in section 2.2.1 Contacts Page, there would be a link to the contacts page?

**Comment by aboydnw** [comment]
@oliverroick I more had in mind the top nav elements. So if somebody is midway through the user guide, finds the info they need, it should be easy for them to navigate to another page. I could see how the solution you suggested would solve this need as well, though.

I think in general we are looking for the least cost, most widely used solution. so making the top nav sticky might solve more use cases, in my mind. However, if we implement an accordion type functionality or table of contents sidebar, maybe the top nav doesn't need to be sticky.

**Comment by aboydnw** [comment]
@oliverroick the text in the document linked above is not quite ready, so we can hold off on that for now. we can update the text later on using the markdown file.

**Comment by deborahUAH** [comment]
remaining work in #530
