### ISSUE TITLE
Clarify Workflow Progression through an ATBD

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#476]
### Feedback received from NASA testers:

It was not immediately clear how to navigate through an ATBD. One tester assumed marking "complete" all the required sections within the top level sections like Identifying information or contact information, the tool will prompt me to start the next step at the bottom of the page (expectation/reference from filling out an online form or questionnaire). The user had to  scroll back up and around to notice the top right hand side section header with the down arrow to open up the drop down menu and select the next section- not intuitive enough.   Is marking complete expected at end or during completin of ATBD?

### Context

This ticket focuses on the functionality to save information and progress through the different sections of the report. There are three areas of functionality this focuses on, highlighted below.
![image](https://user-images.githubusercontent.com/92742765/157137926-49d11abe-1217-4425-b270-4d2f68a276e9.png)

1. The Save button
2. The report sections dropdown
3. The Complete dropdown

- Clicking the save button saves the information input by the user.
- Selecting a section from the report sections dropdown progresses the user to a new section of the report.
- Marking a sub-section as complete updates the overall progress tracker of the report, to help in tracking progress and collaborating on different sections.

### Acceptance Criteria

- [ ] It should be clear to users why they might mark a sub-section as Complete through helper text, info icon, or some other similar functionality
- [ ] There is a Next Section button at the bottom of the form that progresses the user to the next section and saves their progress

**Comment by aboydnw** [comment]
@deborahUAH based on the feedback on the "Mark As Complete" dropdown for the sub-sections, I am wondering how often this will be used? In the description above I put, "Marking a sub-section as complete updates the overall progress tracker of the report, to help in tracking progress and collaborating on different sections."
The main use case I could see is if people are collaborating on the same sub-section and they want to formally mark it as complete so they can move on to another section. 

If it is just one user filling out the ATBD, marking sub-sections as complete might be extraneous. So, maybe we do away with this functionality and just track progress based on where there is any text entered into a sub-section?

Curious to get your thoughts here.

**Comment by deborahUAH** [comment]
The main use case is the multi-author scenario, and I would hate to remove the capability only to have a request to put it back!  Perhaps the way to solve some of the issues is to plan to send a new author (after sign up) a basic information email that gives some important workflow tips - such as using the "mark as complete" button and how to add additional co-authors?  As an author, I would find it helpful to be able to mark sections as complete so I can stop thinking about them.  It would be super helpful if when a section is marked as complete, the drop indicated this somehow (check marked or crossed out section name?)

**Comment by aboydnw** [comment]
That's a great idea! Some sort of visual cue that it is complete and that it is a good thing.

We can brainstorm a bit more on our end on how to clear this up for the users. If at all possible, I would prefer to solve this in the user's workflow rather than as a user guide or separate training communication. It's such a small thing, they'll probably have to be reminded a few times.
