### ISSUE TITLE
Contact Selection

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#478]
### Feedback from NASA testers

The list of Contacts will become quite long, so there should be an easier way to select from the possible options.

### Acceptance Criteria

- [ ] Users can easily find and select the contact when there are many potential contacts (say, 100+)

### Implementation Notes

Something as simple as alphabetizing the list of contacts could be enough, especially if the user can type the first few letters of the contact's name to find them.

**Comment by aboydnw** [comment]
@deborahUAH marking this one as out of scope for now because the field allows search capabilities. I would suggest waiting until the Contact list grows and seeing if people have issues with using this form field in this way before spending development time addressing it. 
![image](https://user-images.githubusercontent.com/92742765/157788589-900b5754-b5d8-4e59-98be-41083b031205.png)

**Comment by deborahUAH** [comment]
agree. we can pick this back up if we continue to have user issues with finding contacts.

**Comment by aboydnw** [comment]
Closing as stale, will reopen if necessary.
