### ISSUE TITLE
Tables - Keyboard Nav

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#479]
### Feedback from NASA testers

> user should be able to use tab to move between cells in a table or to move to the next box in a multiple entry such as first name, last name situation

### Acceptance Criteria

- [ ] User is able to use standard keyboard navigation to move between cells

### Implementation Notes
Potential nav capabilities

1. Tab moves to next cell left to right then top to bottom
2. Shift+tab goes in reverse order
3. Enter moves down a cell

**Comment by aboydnw** [comment]
@deborahUAH marking this one as out of scope because there are currently existing keyboard shortcuts in the ATBD tables. The tab key does not move across cells, but the arrow keys do. You can also add rows, columns, and delete rows and columns using keyboard shortcuts.

**Comment by deborahUAH** [comment]
That is ok.  I will add to the user guide the details of moving through a table with arrow keys instead of tab key.

**Comment by aboydnw** [comment]
Closing as not planned based on conversation above.
