### ISSUE TITLE
Alias field allows user to enter dash

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#481]
### The feedback received during NASA validation testing was:

1. The Alias field does not allow entry of dashes

### Acceptance Criteria

- [ ] Alias field allows the user to enter dashes

Alternatively, we could remove this field.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH Do we have a status on this?

**Comment by deborahUAH** [comment]
low hanging fruit is to make sure the UI information says what users can do - i.e. do not say a dash is ok to use.

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH what's the value/rational for this ticket?

Currently, if you type out the name of a document, spaces are converted into dashes in the alias field. Users can't enter dashes manually into the alias field.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/25919630/230133053-be039101-8a72-4cd2-8528-08485dffa9fd.png">

**Comment by bwbaker1** [comment]
@wrynearson The user instructions should just be updated to "Only alphanumeric characters are allowed."
The current instructions read as though users can manually enter dashes.

**Comment by deborahUAH** [comment]
We had this discussion with a previous team....   The issue is that having the alias field present suggests a user can alter it.  When they try, they can not add dashes and therefore get frustrated.  At that time, we suggested removing the alias from user view thinking that no one really needs to see the alias.  Is this true, do you all agree?  @wrynearson @bwbaker1 @ashleyriddle92 ?

**Comment by wrynearson** [comment]
@deborahUAH I think the title is more important and visible, but the alias is what is in the URL, so users _might_ care a bit about it. I don't know if users need to have dashes, and we tell them that only alphanumeric characters are allowed, so I'm not sure if our current approach is frustrating for users.

**Comment by deborahUAH** [comment]
The frustration was mentioned by users in testing a year ago.

**Comment by deborahUAH** [comment]
Let's assess the effort required to remove it from the user view.  If too much (> 1hr effort) then leave as is. We will adjust the UI text to improve user understanding.

**Comment by bwbaker1** [comment]
@wrynearson After some testing, there is a workaround to add dashes by using cursor control keys. Not sure if this justifies not removing the field from users view though. See screen recording.



https://user-images.githubusercontent.com/56319064/230166241-db0185db-047d-429f-b067-80b21d607657.mov

**Comment by wrynearson** [comment]
Nice find @bwbaker1 🙌

**Comment by wrynearson** [comment]
This wasn't on the value Miro board. I [made a new sticky](https://miro.com/app/board/uXjVMWs_ouY=/?moveToWidget=3458764550990658632&cot=14) note for this. Could you let me know the value of this and I'll put in on the board?

**Comment by bwbaker1** [comment]
@wrynearson Let's just update the UI text from "Only alphanumeric characters and dashes are allowed." to "Only alphanumeric characters are allowed." There is the workaround to add dashes, but let's just keep this simple for now.

**Comment by bwbaker1** [comment]
@wrynearson This looks good.

**Comment by wrynearson** [comment]
Closed with https://github.com/NASA-IMPACT/nasa-apt/issues/510
