### ISSUE TITLE
Update Black to 22.3

### ISSUE THREAD

**Issue by vincentsarago** [NASA-IMPACT/nasa-apt#487]
https://github.com/NASA-IMPACT/nasa-apt/blob/eea44b88051abc3147588e5212eaa4de93e8808d/.pre-commit-config.yaml#L2-L7

https://github.com/developmentseed/rio-stac/blob/master/.pre-commit-config.yaml#L1-L7

There is a dependency bug with black <22.3

cc @leothomas

**Comment by leothomas** [comment]
Amazing! Thank you so much!

**Comment by leothomas** [comment]
Addressed in PR #488
