### ISSUE TITLE
Migrate to CDK v2

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/nasa-apt#493]
CDK v1 will reach EOL on June 1st 2022.

**Comment by sunu** [comment]
On June 1, 2023, AWS CDK version 1 reached the end-of-support. We should migrate as soon as possible. cc @wrynearson

**Comment by wrynearson** [comment]
Update @bwbaker1 – we'll deploy this on Wednesday, Aug 9. There's a chance it will break staging, so if so, we'll debug it with @leothomas on Thursday, Aug 10.

**Comment by bwbaker1** [comment]
@wrynearson I think this is good to go. We haven't found any issues on staging - maybe nothing was broken.
