### ISSUE TITLE
Spike: Inline Latex equations

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#494]
### Description

The current APT text editor allows the user to add text, tables, figures, or Latex equations. When a user adds a table/figure/equation, it is inserted as it's own "block" or "item." This provides clear definition for the user when they are editing different parts of the report. Through the flow of the report, these items stand out as separate from the text, as is common in technical documents. However, throughout a report there will be a need to reference part or all of an equation in the text. The full equation will likely be identified using the existing functionality, and the authors will need to insert a piece of this larger equation when adding descriptive text.

![image](https://user-images.githubusercontent.com/92742765/163897630-14a5ae85-2255-4128-8f8c-42e5c0ef93f2.png)
![image](https://user-images.githubusercontent.com/92742765/163897817-8dfa7aab-175f-48ce-a673-4b73e558b189.png)

### Acceptance Criteria

1. A plan and associated tickets for implementing inline latex equations, ideally reviewed or collaborated on with a designer (Ricardo would be good)

**Comment by oliverroick** [comment]
_Noting down some initial ideas for this:_

[User feedback](https://github.com/NASA-IMPACT/nasa-apt/issues/411) suggest that we could support Latex syntax to enable inline equations by wrapping the equation between `$`, ie. `$e=mc^2$`.

This approach would break with the concept of WYSIWYG, whereby markup isn't shown in the editor, and the text is shown as it would appear in the final document.

To enable inline equations alongside block equations, we need to extend the existing equation plugin I the following ways: 

- Open the equation editor in a modal, which is required for editing inline equations. We won't be able to display the editor in the same way we do for inline equations. Inside the modal the equation editor will work in the same way as the existing editor: An input to edit the equation using Latex  syntax and a preview rendered using Katex
	- Clicking on an equation should open the equation-editor modal. 
	- Clicking the plugin button in the editor toolbar _without selecting text_ will open the editor model with the example equation.
	- Clicking the plugin button in the editor toolbar _with text selected_ will open the editor model and the selected text will be pre-filled in the equation input.
	- Saving the equation will close the modal and update the equation rendered in the text. 
- Extend the editor to allow selecting if the equation should be displayed inline or as a standalone block. This requires introducing a new container element for inline equations and changes to how equations are rendered within the Slate editor. 

I think this work should be broken out into two tickets:

1. Convert the existing editor to the modal-based implementation only supporting block-level equation.
2. Extend the editor to support inline equations and change rendering accordingly. 

@ricardoduplos would be good to get some feedback on the UX of this approach. /cc @aboydnw @danielfdsilva

**Comment by aboydnw** [comment]
Something that comes to mind here @ricardoduplos @oliverroick are all the different states for equations within the text editor. For both the inline and block equation use cases, what does it look like in the WYSIWG compared to what does it look like when the user hovers over it and perhaps even when they click on it? With this addition there are probably some visual considerations like that.

**Comment by ricardoduplos** [comment]
@oliverroick @aboydnw I support this approach. Seems functional and well integrated.

I have some questions on how to edit or delete an equation, selecting vs clicking behaviors, etc. For that: I'm wireframing some options. I'll share the results here.

**Comment by aboydnw** [comment]
@ricardoduplos thanks for putting together these wireframes. Looking through them and talking it through with @oliverroick , I can't think of any changes to make. I think IMPACT will be really happy with this functionality.

**Comment by danielfdsilva** [comment]
Closing in favor of https://github.com/NASA-IMPACT/nasa-apt/issues/502
