### ISSUE TITLE
Push Post-Testing Feedback Changes to MCP

### ISSUE THREAD

**Issue by oliverroick** [NASA-IMPACT/nasa-apt#495]
This should be quite easy to deploy to MCP because there are no updates needed for the database or any other elements of the backend, just updating the API docker image. The process therefore is:

**Pre-requisites:**

Shawn needs to start up the "jumpbox" EC2 instances in UAH and MCP

**Process:**

1. ssh into UAH jumpbox EC2
2. ssh from UAH jumpbox EC2 to MCP jumpboxEC2
3. pull updated code from github
4. run `cdk deploy nasa-apt-api-lambda-prod` (verify deployment goes through)
5. run `aws ses verify-email-identity --email-address no-reply@apt-admin.org` (then whoever has access to that inbox needs to click the validation/verification link)

**Comment by aboydnw** [comment]
Release document representing the work: https://docs.google.com/document/d/1wk5b1CwJhDgkTHLQ4jw6RqqFArsF5p6t7gRTq9t-AAQ/edit#

**Comment by aboydnw** [comment]
Closing as duplicate
