### ISSUE TITLE
Editing title causes 404

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#507]
Reproduction steps:

1. Create a report
2. enter a title
3. Save the report
4. Publish report
5. Edit published report
6. change title
7. change focus out of title field (by clicking, tab, etc)
8. notice error in console, and notice that save button isn't active until you change focus, even though unsaved changes warning appears
9. click Save
10. get error

I go this error when attempting an a draft report, even though the change goes through just fine:
![Image](https://user-images.githubusercontent.com/92742765/171963613-6e94dcc1-f919-44a0-bf6e-fcb4a97e564d.png)

When I edit a published document, I get the same error as above (highlighted below) except now when I click save I get a 404 page. I noticed the new title is in the URL, maybe that has something to do with it?
![Image](https://user-images.githubusercontent.com/92742765/171963869-d13677bc-c0c7-4fbc-94b5-02a043fb76df.png)

**Comment by oliverroick** [comment]
I can't reproduce this following the steps above. Can we discuss this during our office hours.

**Comment by aboydnw** [comment]
After attempting to recreate this again, it looks like this only happens if the alias field was empty when the document was first created/published. There are two fixes we would like to put in place to avoid this:

1. Remove default text from Title field of "Untitled Document"
2. Make the alias field a required field

**Comment by aboydnw** [comment]
Okay, great! I think that edge case is way further out on the edge than how it performs today. I say we go with it and call it good unless we see a bunch of user issues come up.
