### ISSUE TITLE
Generating PDF after editing published document gets Internal Server Error

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#508]

**Comment by aboydnw** [comment]
@deborahUAH I have been trying to reproduce this and failing. Are you still able to produce this error? and if so, could you include steps and screenshots?

**Comment by leothomas** [comment]
Addressed in release [v2.4.0-beta](https://github.com/NASA-IMPACT/nasa-apt/releases/tag/v2.4.0-beta)

**Comment by aboydnw** [comment]
Closing based on comment above.
