### ISSUE TITLE
[WIP][Discussion]: Ensuring data persistence in S3 and Elasticsearch 

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/nasa-apt#509]
# Context/Background:

The data that a user supplies when editing an ATBD is persisted in 3 different places: 
1. a PostgreSQL database, hosted in AWS RDS
2. a PDF document, hosted in AWS S3
3. an elasticsearch instance, hosted in AWS OpenSearch

While an ATBD is still in the editing/review stages, its data is stored only the database. PDFs can be generated for the ATBD, but, since they are still considered "drafts" they are not persisted anywhere. Once the ATBD is published, the journal and regular PDFs get generated and persisted to S3, and the document is indexed in Elasticsearch. 

Once an ATBD is published, users have the ability 1) increment the minor version and 2) create a new major version, from the current major version. When a user increments the minor version, whatever changes have been made to the ATBD version overwrite that ATBD version in the database. This means that the database stores _only_ the most recent minor version. This decision was made on the basis that 1) maintaining records for each major and minor version would lead to a _very_ complex database design (essentially entailing a branching workflow model) and 2) minor version updates are supposed to occur only for small, non-essential changes (typos, formatting edits, etc), which aren't crucial to maintain within the document's history.  

However, the Impact team requested that the PDFs for each minor be accessible (this seemed to be as a "just in case" measure, since the APT cannot enforce proper usage of the major/minor versioning system,  users _might_ make a big enough change when incrementing the minor versions that would still want to access previous minor version PDFs).

The solution was to generate both the journal and regular PDFs whenever a user publishes a major version, or increments a minor version. This is why it the response from the backend sometimes takes a long time when publishing an ATBD or incrementing the minor version: under the hood, the API is generating both PDFs and indexing the ATBD in Elasticsearch. Indexing each minor version in the Elasticsearch wasn't a requirement set by Impact, but it seemed logical to us (if you can download a specific minor version of an ATBD you should probably also be able to search for it). 

As an example, here are all the copies of a hypothetical ATBD, that is currently on it's 3rd major version: 
```text
Elasticsearch (searchable): 
- v1.0 
- v1.1
- v1.2
- v2.0
- v2.1

S3 (PDFs): 
- v1.0 
- v1.1
- v1.2
- v2.0
- v2.1

Postgres (RDS): 
- v1.2
- v2.1
- v3.0 # <-- not yet published
```

Storing PDFs and indexing new minor versions in Elasticsearch was implemented using FastAPI's [background tasks](https://fastapi.tiangolo.com/tutorial/background-tasks/), however, since the API is implemented in a Lambda function, the Lambda function has no notion of threads and background tasks, so it simply runs the background tasks within the same execution context as the request, _before_ returning the API result to the user. This is one of the disadvantages of using FastAPI in Lambda.

## The problem: 
We recently encountered an issue in staging where the Elasticsearch instance crashed and somehow restarted. I'm not able to figure out either why the instance crashed in the first place, or which of my actions in the AWS console got the instance back to a reachable state (since the AWS console still shows the instance status as "in progress"), however I suspect the issue may be similar to what [these people have experienced](https://github.com/aws-amplify/amplify-category-api/issues/165).

In our case, all of the previously indexed ATBDs were lost (and are therefore no longer searchable). What's more is that there is no way to re-index previous minor versions in Elasticsearch, since they were overwritten in the database. In the example above, we would only be able to recover the documents indexed in Elasticsearch to this state: 
```text
Elasticsearch: 
- v1.2
- v2.1
```
(missing `v1.0, v1.1, v2.0`)

Similarly, if, for some reason the indexing process fails when creating a new minor version, the data in database will be updated, but nothing will retry the failed indexing operation. 

Similarly for the PDF generation: if the PDF generation fails when a user publishes a document or increments the minor version, there will be no way for the user to regenerate those PDFs, and they will be missing from S3 (which might also cause problems in the frontend since, the "Download PDFs" button expects past minor versions to be available to download).

# Problem: 
The problem can be summarized as: since we do not store each minor version individually, missing PDFs and indexed documents cannot be recovered if they are lost, or fail to generate in the first place.

# Solutions: 
At first glance there are 2 solutions: 
## 1. Abandon the requirement for minor version PDFs and searchable documents (low lift - requirements based)
This is the easiest solution since it allows us to index whatever documents are in the database, and, if ever we loose all the data in the Elasticsearch instance, we can simply re-index everything that's in the database. 

This kind of bluk operation is obviously not ideal if we have tens of thousands of records in the database, but we don't anticipate that kind of usage, and we don't anticipate the ES instance crashing often (just often enough to be a problem). 

Similarly, we abandon the requirement to persist any documents in S3, and we simply regenerate the most recent minor version from whatever is stored in the database every time a user clicks "Download PDF". 

I would argue that this is an acceptable solution on the basis that minor versions are only supposed to be used for minor edits, so indexing and persisting PDFs for each minor versions is not really storing any meaningfully different or new data (as long as users are using the versioning system as intended).  

## 2. Re-inforce the indexing/PDF persisting (high lift - technical solution)
If we want to maintain the requirement that past minor versions are searchable and accessible as PDFs, there are a couple different approaches we can take: 
### 2.1. Make PDF generation and ES indexing a blocking workflow: 
The problem lies in the fact that user can increment the minor version, and if the minor version update goes through successfully but the PDF generation or ES indexing fails, even if the user knows about it, the operation cannot be retried. A solution to this is to make the PDF generation and ES indexing a blocking part of the workflow. This means that when the user goes to publish the document or increment the minor version, if the PDF generation or ES indexing fails, then the whole operation fails, and the minor version number will not be indexing in the database. This would ensure that documents are indexed in ES and PDFs are generated for each minor version increment, at the expense of a possibly poorer user experience, since they might now be blocked from publishing their document because of a PDF generation error outside of their control. (This would also catch (and block) the case where users attempt to publish a malformatted document, that would result in broken PDF generation or ES indexing. 

This solution alone does not protect us from the Elasticsearch instance crashing and loosing all data, so we would also have to persist indexable documents to S3 before indexing them in Elasticsearch, so that we can re-index from S3 if needed. 

### 2.2. SQS Queue based workflow
When users update a minor version or publish a new version we send the updated document to an SQS queue, where it is processed by a separate lambda function. This constitutes "proper" background processing.

SQS Queues comes with auto-retry behaviour and exponential backoff, in case the ES indexing or PDF generation operation fails, and a dead-letter queue for any message that fails to process 5 times. We can hook up the dead-letter queue to some sort of notification system in order to handle the exception manually (* Note: I don't really have an idea of what handling a failure case like this one "manually" would entail). 

Since the SQS Queue alone wouldn't protect us against issues with the Elasticsearch instance crashing and loosing all data, we would also likely want to persist the ES indexable documents to S3 before indexing them so that we can re-index from S3 if needed (if the ES instance crashes).

*Note*: AWS Opensearch service supports both Elasticsearch and Opensearch, which is AWS's open-sourced version of Elasticsearch, since the group behind Elasticsearch modified the license and won't be providing update to Elasticsearch anymore. The APT backend still uses Elasticsarch. While migrating from Elasticsearch to Opensearch should be relatively easy, since AWS maintains backwards compatibility with Elasticsearch, and it would _likely_  help reduce the chances of data loss due to crashes in the futures (since it will be actively maintained by AWS going forward), it isn't guaranteed to resolve the issue of losing indexed documents due to the service crashing, and it doesn't resolve the issue of missing documents due to failed indexing / failed PDF generation

#### Lift: 2 FT sprint

**Comment by leothomas** [comment]
[UPDATE: Decision made]

Handle using options 2.1 above: make elasticsearch indexing and PDF generation a blocking workflow.

**Comment by wrynearson** [comment]
@sunu @thenav56 is there any value to keeping this ticket open, or can I close it?
