### ISSUE TITLE
Update text throughout APT

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#510]
This ticket is for small text tweaks (not related to the Help page) that NASA caught during testing in May, 2022.

[Current Spreadsheet](https://docs.google.com/spreadsheets/d/1WGOneLzU6dF-pqaYevQujvGQniutkVx3MQCj9gcPuN4/edit#gid=0)

**Comment by aboydnw** [comment]
@deborahUAH do you have the word doc/spreadsheet that you mentioned that shows the text changes you want to see in the tool?

**Comment by deborahUAH** [comment]
not yet. I am the hold-up there. Still working through the user guide changes.

**Comment by deborahUAH** [comment]
This issue is now in Q4.

**Comment by wrynearson** [comment]
@frozenhelium most of these changes have been made, but there are few remaining ones

**Comment by bwbaker1** [comment]
@wrynearson Is this something that would be rather quick/easy to finish up?

**Comment by wrynearson** [comment]
@bwbaker1 I'd need to see the proposed text changes before confirming 100%, but 99% yes this will be quick and easy.

cc @batpad

**Comment by bwbaker1** [comment]
@wrynearson I reviewed the [spreadsheet](https://docs.google.com/spreadsheets/d/1WGOneLzU6dF-pqaYevQujvGQniutkVx3MQCj9gcPuN4/edit#gid=0) and checked off prompts that are already implemented.  There are several prompts that need to be changed, but I think these should be relatively easy fixes (e.g., Url --> URL).

**Comment by wrynearson** [comment]
Thank @bwbaker1, that will be easy to implement

**Comment by bwbaker1** [comment]
@wrynearson Here is the updated [UI text](https://docs.google.com/presentation/d/1ATn2WE8tzyQunRZdNSD7ytPGAIMakccTPI4BvKeXOIs/edit#slide=id.p). For each image, I placed numbers to indicate where the change is needed and the comment is the needed text change. Let me know if that doesn't make sense or is too confusing. I thought it may be easier than trying to use the previous spreadsheet.

**Comment by wrynearson** [comment]
Thanks @bwbaker1 ! That's very helpful. I'll get to updating all of this soon

**Comment by wrynearson** [comment]
@bwbaker1 in addition to the changes in the slides and the comments I left there, I updated the step titles to be capitalized

<img width="340" alt="image" src="https://user-images.githubusercontent.com/25919630/236416917-46b511b1-b602-44ae-99f0-2f2d32d3455a.png">

**Comment by wrynearson** [comment]
@bwbaker1 the text updates are done, but a colleague probably won't be able to review it today. I'll message you next week once it's on staging.

**Comment by wrynearson** [comment]
@bwbaker1 The text changes will be on staging in ~15 minutes and are ready for your review.

**Comment by wrynearson** [comment]
@bwbaker1 this was included in the production deployment on Friday (May 12)
