### ISSUE TITLE
Implement unit/integration tests

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#529]
It would be good to have this on both the frontend and backend before we hand over the project to ESDIS.

Currently, we have some tests for the backend but don't have them for the frontend.

## Acceptance Criteria
- [ ] Tests as outlined during spike are implemented
- [ ] Implement frontend tests
- [ ] Implement backend tests

cc @batpad

**Comment by wrynearson** [comment]
Closing this in favor of https://github.com/NASA-IMPACT/nasa-apt/issues/659
