### ISSUE TITLE
APT blog post

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#532]
### Description: 
We need to increase the science community's knowledge of APT.  A part of this includes publishing a blog post on IMPACT's Medium platform.

### Tasks:
- [x] Draft and write blog post (0 pt)

### Acceptance Criteria:
- [x] Published blog post describing APT

**Comment by deborahUAH** [comment]
Blog post on APT released. See [post](https://impactunofficial.medium.com/new-tool-advances-algorithm-publication-2cb993894e8c)
