### ISSUE TITLE
Determine security requirements in NGAP

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#535]
### Description: 
Part of moving to NGAP is that APT needs to meet all of NGAP's security requirements. 

### Tasks:

- [x] Set-up and have meeting to determine the needed security requirements.
- [ ] Identify any required fixes and determine how to address such fixes. (1 pt)

### Acceptance Criteria:
All security requirements are identified.

**Comment by wrynearson** [comment]
I think this is a duplicate of https://github.com/NASA-IMPACT/nasa-apt/issues/536? If so, can we close one of the two?

**Comment by bwbaker1** [comment]
@wrynearson It is a duplicate. I am closing this one and leaving #536.
