### ISSUE TITLE
Epic: Adjust APT as needed to meet security requirements

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#536]
**EPIC:** APT Future Planning

**Description:** NGAP security requirements have been identified and now need to be implemented. 

**Tasks:**
- [ ] Complete all identified fixes/changes needed for meeting NGAP's security requirements. (0 pts)

**Acceptance Requirements:**
- [ ] APT meets all of NGAP's security requirements.

**Comment by oliverroick** [comment]
@bwbaker1 Is there a list of identified fixes and changes that we need to implement?

**Comment by bwbaker1** [comment]
> @bwbaker1 Is there a list of identified fixes and changes that we need to implement?

I haven't worked on this task - just created the issue.  @deborahUAH @michaelsfoley See Oliver's comment/question.

**Comment by deborahUAH** [comment]
There was one meeting with NGAP folks and no list resulted.  I expect to meet with them again next sprint to identify detailed needs.

**Comment by deborahUAH** [comment]
Per Doug Newman and Valerie Dixon (ESDIS): Cognito is in NGAP.  Some information resources are on the Earthdata Wiki [here](https://wiki.earthdata.nasa.gov/display/EDO/Cognito+Settings+Do's+and+Don'ts+Meeting+Notes) and [here](https://wiki.earthdata.nasa.gov/display/ESKB/AWS+Services+Approval+Status+Page) and [here](https://wiki.earthdata.nasa.gov/display/ESKB/Security+-+Policies+and+Best+Practices).  
You need Earthdata login to access these pages.

**Comment by oliverroick** [comment]
@deborahUAH I created an Earthdata account but I'm unable to access any of the linked pages. Do I need special permission, is access restricted to certain countries (I'm accessing from Australia)

**Comment by deborahUAH** [comment]
@oliverroick   you likely need to let the Earthdata folks know you need access.  Access is not restricted to certain countries. The wiki pages just have public pages and authorized pages.  State you are working on APT as a developer and need to access those URLs for reference and they should make it happen.  I just tried to share the above links with you. Let me know if that worked.

**Comment by oliverroick** [comment]
@deborahUAH Who do I need to state this to?

**Comment by deborahUAH** [comment]
I shared the documents with you, if you still can't access them, then send an email using the feedback tool (top right of page) to explain that you are DevSeed working on APT and need access to understand security requirements for APT transition to ESDIS. Let me know if you do not get a response.  Make sure you have logged in with your earthdata login first.

**Comment by oliverroick** [comment]
I've requested access via the feedback form.

**Comment by wrynearson** [comment]
Closing this as stale. IMPACT should reopen this ticket once we're ready to transition
