### ISSUE TITLE
Commenting should not be available to public users

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#542]
Commenting does not work for public users, but is available. We should hide this functionality

![Image](https://user-images.githubusercontent.com/92742765/180251108-a4b5020a-5d21-4f1e-bdb1-1a294ebfb313.png)

**Comment by oliverroick** [comment]
@aboydnw Should public users be able to see existing the comments without being able to leave a comment? Or should they not be able to see the comments at all?

At the moment, only the comment panel opens but no comments are shown (not even a request to send comments is shown, so I'm assuming public users shouldn't be able to see comments at all.

**Comment by aboydnw** [comment]
@oliverroick Thanks for clarifying. They should not see comments at all. So even the little comment button that appears when you hover to the left of a section header should not appear. That should only appear for collaborators of a document and curators.

**Comment by aboydnw** [comment]
@oliverroick I assume that this is not yet pushed to MCP, right? What is our process for pushing changes to MCP? Should we have some regular interval for doing that?
