### ISSUE TITLE
Epic: Upload Previous ATBDs to APT

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#543]
## Description

ATBDs already exist in the world. The eventual goal of APT is to become the source of truth for ATBDs, so we will likely need some way for already existing ATBDs to be brought under the APT umbrella. The current workaround is to have people copy and past ATBD information into a new APT document. This is not feasible at scale. 

Ideally, users could upload pdfs of existing ATBDs and have those ATBDs exist alongside new versions that are curated and iterated on in APT. One of the biggest question marks is, even if we upload PDFs, how do we upload _information?_ So that we avoid the problem of people having to copy and paste information from PDF into APT. 
And if we solve that, what does this mean for the versioning system? Does it need to recognize when an old ATBD has been uploaded?

I am sure there are other complexities, but these questions have come up when discussing in the past.

**Comment by aboydnw** [comment]
@naomatheus @oliverroick I created this ticket based on conversation during the tagup today. It is not a ticket for this PI, but a potential future ticket. In the past, we have pushed it off because it has seemed very complex. Curious to get your thoughts on it as some point.

**Comment by aboydnw** [comment]
@wrynearson fyi for potential future development of APT

**Comment by wrynearson** [comment]
Do _all_ previous ATBDs have the _exact_ same PDF layout/format? Or are there several standards? Or are there many? I think the answer to these questions will affect the complexity of this story significantly.

**Comment by deborahUAH** [comment]
All previous ATBDs will not conform to any existing template.  The idea would be to retain the PDF for download and to have the curator add the vital metadata for searching and listing in the APT dashboard with PDF view model only.  NASA will probably never pay for all historical ATBD content to be entered into the APT template, so we would need a way to include as PDF and provide in searches for discovery.

**Comment by deborahUAH** [comment]
Discussed with Kumar the idea of using ChatGPT or equivalient to extract content and determine metadata for existing ATBDs whether in Word, Google Doc, or PDFs.  This is one cost-effective means to add existing ATBDs to APT.  At a minimum, curators could add title and authors and publication date - some basic metadata and have PDF in APT.  Need to design what this would look like.  
Adding this to FY24 work

**Comment by wrynearson** [comment]
Hi @deborahUAH, there are two large issues with using ChatGPT or other generative AI.

Introducing generative AI (ChatGPT) runs a very large risk of generating inaccurate information. While ChatGPT is very good at synthesizing information, it often does so inaccurately and confidently (i.e., it's hard to tell that it's wrong). Adding incorrect information to ATBDs, especially with real people's names and real people's work, could definitely lead to some unhappy comments from authors. [It has already fooled scientists](https://www.forbes.com/sites/brianbushard/2023/01/10/fake-scientific-abstracts-written-by-chatgpt-fooled-scientists-study-finds/?sh=5a208e4418b6).

The other issue is that generative AI, as the name suggests, excels at _generating_ and _synthesizing_ content, not extracting content. It would not be suited to know which paragraphs belonged to which sections. It could write abstracts of an ATBD, but it runs the risk of the first issue, not to mention that ATBDs already have abstracts. It could be used for metadata creation, but again, I think that information already exists in most ATBDs.

If the goal is to get old ATBDs into APT, then we should assess:
1. Why we want to have old ATBDs in APT (are we envisioning APT to be a repository/one-stop-shop to find any ATBD?)
    - Are we sure that users want that? We should conduct user research to make sure
2. If we do want old ATBDs in APT, do we need to have them in a standardized format, or could we just host PDF/Word docs?
    - If its just hosting docs and adding some metadata, we could see point 3
3. If we want to have old ATBDs (in a standardized format or just some metadata), how many ATBDs do we want to import? 10? 100? 10,000?
    - If the answer is a low amount, we could (painfully) do it manually. It probably would take far less time to copy/paste than it would to develop novel approaches.
    - If the answer is a high amount _and_ most of them follow a standardized format (or several), we could explore automating the process
    - If the answer is a high amount _and_ they all have different formats, we should be very confident that this would be a valuable feature before exploring possible solutions.

For metadata generation, there are some [existing approaches](https://www.analyticsvidhya.com/blog/2022/03/keyword-extraction-methods-from-documents-in-nlp/) to generate keywords.

cc @bwbaker1 @batpad

**Comment by wrynearson** [comment]
Update – @deborahUAH estimates there to be ~100 to 150 existing ATBDs under NASA's purview

**Comment by bwbaker1** [comment]
Update - it was discussed there are probably 2000+ existing NASA ATBDs.

**Comment by deborahUAH** [comment]
This can be closed as the alternative is to use an Earthdata repository for historical ATBDs with SDE search capabilities.  APT will not need to incorporate existing historical ATBDs

**Comment by wrynearson** [comment]
@bwbaker1 could you share how the number 2000 was settled on? I wonder how the previous estimate was an order of magnitude off.

@deborahUAH, are you saying that APT will _never_ need to incorporate historical ATBDs, or just that it's not a priority? I think this is a pretty big change. I'll close this as "not planned" (which lets us differentiate between completing something)

**Comment by deborahUAH** [comment]
Per conversation with Rahul today (4/6) the decision is for APT to incorporate completed ATBD PDFs - especially for those written currently using the template.  Sorry for the changes but the discussions this week are resulting in continuous changes.  @bwbaker1 will provide details for estimating effort and time. We need this delivered this quarter. Bring possible approach to Tuesday's meeting

**Comment by wrynearson** [comment]
@deborahUAH @bwbaker1: 

> We need this delivered this quarter

We can't guarantee any sort of delivery timeframe until we have this request better scoped out. 

Several initial questions:
1. What level of incorporation is being requested? Will PDFs sit on a webpage for users to download, will they be searchable, or will they look like current APT ATBDs in view mode?
2. Will users have two methods of writing ATBDs (APT and external templates)? Multiplying user pathways also runs the risk of multiplying confusion and maintenance overhead.
3. Is this _including_ previous ATBDs (which don't have a consistent structure) or just newly written ATBDs?

**Comment by deborahUAH** [comment]
Per recent conversations, level of incorporation is upload capability with form for inputting basic metadata (i.e. title, authors, abstract, completion date, etc - TBD).  All PDFs are stored in a repository.  All repository documents are searchable and accessible by public users.  This upload capability will include historical PDF uploads with no concerns about inconsistent historical structure and content of historical PDFs.    Users will have choice of using template to author an ATBD or using the APT environment.  Both means will produce an ATBD in PDF form that will be entered into the repository with basic metadata for searching.

**Comment by wrynearson** [comment]
For future clarification – this epic is a part of https://github.com/NASA-IMPACT/nasa-apt/issues/726 and tickets marked with the label https://github.com/NASA-IMPACT/nasa-apt/labels/PDF%20Upload (in this repo and https://github.com/NASA-IMPACT/nasa-apt-frontend)
