### ISSUE TITLE
Change Delete capabilities and confirmation modal

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#548]
## Description

Currently, as a curator you can delete a document. When you click Delete from the menu of options, you get the following modal.

![Image](https://user-images.githubusercontent.com/92742765/183482120-ce1cb034-e89e-4d44-bf46-ca8ce360ccf6.png)

This makes it seem like you are just deleting the version. However, it deletes the entire document. Should we only be deleting the current version? Or should this delete the entire document?

As a contributor, you are allowed to delete a draft. When this draft is v1.0 then the document is deleted entirely. When this draft is v2.0 then only the draft version is completed and you are reverted back to the most recently published minor version. 

If a curator is given super delete powers, maybe we should allow them to either a) delete a minor version or b) delete the entire document altogether. We should probably also provide a secondary confirmation modal, similar to how we do when creating a minor version.

**Comment by aboydnw** [comment]
@bwbaker1 I did some digging after the recent mishap with deleting the demo ATBD. It seemed weird to me that you could so easily accidentally do this. Let me know what you think of my writeup above. Might be worth tackling this in the future.

cc @deborahUAH @wrynearson @oliverroick @naomatheus

**Comment by bwbaker1** [comment]
@aboydnw I agree that this should not be an option, especially when the popup states "delete this version." I think your write-up captures the issue.

**Comment by deborahUAH** [comment]
It should not be easy to delete any document.  The confirmation message should be very clear as to what is being deleted.  Just to be clear, a version is a document.  If you delete v1.0, you have nothing.  If you delete v1.4 as indicated above, then APT should only have v1.0, 1.1, 1.2, and 1.3 documents left. I can not think of a time when the curator should need to delete _all_ versions of ATBD.  The message above should have only deleted version 1.4, not all versions of that ATBD and definitely not a published version (the published demo that was available on APT).  **Once an ATBD is published, it must remain in APT forever.**

**Comment by aboydnw** [comment]
After discussing with Deborah, we would like to make the Curator functionality mirror the author functionality. So, if a document is in Draft (this is only possible for new major versions. v1.0, 2.0, etc) then the delete option is available and will delete that draft version. For all other versions, the Delete option should be inactive with the hover explaining only draft versions can be deleted (current functionality for authors)

**Comment by deborahUAH** [comment]
**Restating here what is needed for clarity:**   If a document is in Draft (should not matter whether a major or minor version, it is a _draft version_)then the delete option is available to curators to delete the draft (this handles when a version is created accidentally).  Curators must be able to delete abandoned drafts. 

For all published ATBD documents (in PROD) the Delete option should be inactive for all (except maybe the administrator?) with the hover explaining to a user (authors, curators) that attempts delete of a published doc that only draft versions can be deleted (current functionality for authors)

This will remove the chance that published ATBDs might disappear, but give one role the chance to remove a published doc (like a test) when absolutely needed.

Thoughts?

**Comment by wrynearson** [comment]
I agree – we should have at least one person (one role is probably better, technically) that is able to delete published ATBDs, in case of mistakes or misuse. We will pick this up next PI.

**Comment by deborahUAH** [comment]
adding to next PI

**Comment by bwbaker1** [comment]
@wrynearson I think this ticket is mostly complete - only draft documents can be deleted. I think all that is remaining is to inform users that only draft documents can be deleted. I get a "Request failed with status code 403" when I try to delete a document in review state.

**Comment by wrynearson** [comment]
Noted @bwbaker1, we'll look into it

**Comment by wrynearson** [comment]
1. Catch the error and say that only draft documents can be deleted
2. Check doc status, if not draft, disable delete button

**Comment by wrynearson** [comment]
@bwbaker1 we've updated the UI so that users see disabled (greyed out) grey text that explains why they can't delete a document / version. This is ready for your review.
<img width="1300" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/a1342c58-a331-44d3-a0bf-e244116a2849">

**Comment by bwbaker1** [comment]
@wrynearson Looks good.
