### ISSUE TITLE
Bug: Feedback broken

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/nasa-apt#557]
when I click on the feedback button I get the frown face.  

![Image](https://user-images.githubusercontent.com/88099931/184978597-35c7dfa5-394c-4f1a-8571-1d0de4999577.png)

This has happened before.  Please check for any needed updates to make it work again.

**Comment by deborahUAH** [comment]
please prioritize this effort to get the production APT feedback working again.

**Comment by deborahUAH** [comment]
the feedback button is working in CASEI which tells me it is not a problem with a change in the feedback tool itself (like last time). This is what you should see. 

![Image](https://user-images.githubusercontent.com/88099931/184979617-5a4c90c7-b9dd-4f4b-ad9b-55901d5c3111.png)

**Comment by wrynearson** [comment]
Thanks for flagging this @deborahUAH. 

@oliverroick @naomatheus, in case this helps, I had the same error: `fbm.earthdata.nasa.gov refused to connect.`

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/25919630/185048452-d1218d9c-8827-44dd-8d7b-b755a858b73f.png">

When loading [fbm.earthdata.nasa.gov](http://fbm.earthdata.nasa.gov) in a separate tab, I'm redirected to [the Earthdata login page](https://urs.earthdata.nasa.gov/oauth/authorize?client_id=s4rsYhdUKucCKF5JNZoFkw&redirect_uri=https%3A%2F%2Ffbm.earthdata.nasa.gov%2Fsso%2Fcallback&response_type=code&state=%2F) .

**Comment by oliverroick** [comment]
@deborahUAH 

- The feedback form works under https://impact.earthdata.nasa.gov/apt/
- The feedback form doesn't work under https://www.earthdata.nasa.gov/apt/

It looks like https://www.earthdata.nasa.gov/apt/ needs to be whitelisted for the form to work with specific URLs, which isn't something DevSeed can fix.

**Comment by deborahUAH** [comment]
ok. I will talk with ESDIS folks to get the address cleared.

**Comment by deborahUAH** [comment]
The feedback module maintenance is now handled by the ESDS (Kevin Ward) group.  They have been contacted to arrange for URL whitelisting.  Awaiting response.

**Comment by deborahUAH** [comment]
2nd notice to ESDS sent 9/2/2022 to have URL whitelisted for feedback module to work.  Will follow-up again on Wednesday if I have not heard from them.  Rahul is aware of issue

**Comment by deborahUAH** [comment]
From ESDS web team:
"Technically, there is nothing we can do on our side of the tracks since the responses are originating from the APT web server.

Looking at the response headers from the APT web server:

Server: nginx/1.20.1
* The Earthdata website is running nginx/1.21.5


Referrer-Policy: strict-origin-when-cross-origin

Content-Security-Policy: default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://www.googletagmanager.com/; frame-src https://www.google.com/recaptcha/; frame-ancestors 'self' https://impact.earthdata.nasa.gov/;

Conclusion: The frame-ancestors entry may be the blocker in the Content-Security-Policy header - frame-ancestors 'self' https://impact.earthdata.nasa.gov/;

I suggest adding https://www.earthdata.nasa.gov/ to the to the “frame-ancestors” portion of the header response - like this:


frame-ancestors 'self' https://impact.earthdata.nasa.gov/ https://www.earthdata.nasa.gov/;
@oliverroick @wrynearson

**Comment by oliverroick** [comment]
@deborahUAH I'm attaching a screenshot of the failing request:  

<img width="1773" alt="Screenshot 2022-09-08 at 14 13 55" src="https://user-images.githubusercontent.com/159510/189032814-8ddd6338-446b-4141-81e6-ac019599e4d3.png">

The request goes to https://fbm.earthdata.nasa.gov/, which neither is the APT server nor is it a server that we (as Development Seed) maintain. We can't make the required change; somebody from within IMPACT who administers the server behind https://fbm.earthdata.nasa.gov/ needs to make the change.

**Comment by deborahUAH** [comment]
@xhagrg We need your help with the above feedback module issue.  Please review this ticket and let me know what you advise. Thanks!

**Comment by xhagrg** [comment]
I will check on this first thing tomorrow.

**Comment by xhagrg** [comment]
@deborahUAH 

I went through this issue and looked through the frontend as well. Here's what I found:

1. The `Algorithm Publication Tool` (that's the app name on fbm side) was registered in FBM when it was being hosted at impact.earthdata.nasa.gov/apt. This was working fine.
2. APT then migrated to earthdata.nasa.gov/apt. This change was not reflected on the FBM side, which brings us to the current issue.

To resolve this, the ESDIS team will have to update the configuration for `Algorithm Publication Tool` from impact.earthdata.nasa.gov to earthdata.nasa.gov.

Hopefully this helps. If it's an email you are to send them, please CC me with the details and if they have further questions, I can try and help.

**Comment by deborahUAH** [comment]
Thanks, Iksha.  This is my interpretation too.  Unfortunately, the FBM was
transferred from ESDIS to Kevin Wards team and they tossed it back to us as
nothing they can do.
I will email Andi and state the obvious again as you have written above and
see if a second attempt works. Thank you!  I will cc you on the convo.

**Comment by deborahUAH** [comment]
Confirmation with Kevin Ward that this is an ESDIS issue. He is working it out with them.  I will follow-up with both parties next week.

**Comment by deborahUAH** [comment]
This is a P1 bug and must be resolved this PI.

**Comment by deborahUAH** [comment]
no news from ESDIS or Kevin Ward and feedback still not working on production.  Email nudges sent

**Comment by xhagrg** [comment]
Move to alternatives in the mean time? (Google form should be a simple enough start?)

**Comment by deborahUAH** [comment]
I have created a google form for APT Feedback.  Link is https://forms.gle/JG6ykqj2mAjzke6S6  
@wrynearson @naomatheus  please make the feedback button use this so that users can provide feedback instead of using the FBM/ Kayako system of ESDIS.  Please give me an estimate of when this can be completed by. Thanks

**Comment by wrynearson** [comment]
This was fixed with https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/401. I don't think I have the permissions to approve it, so we might need @naomatheus 's review.

**Comment by wrynearson** [comment]
Hi @deborahUAH and @bwbaker1 , this is ready for testing on [staging](https://nasa-apt.surge.sh/dashboard).

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH I just tested the feedback module on staging.  I like the Google Form and this seems to work.  I tested each type of report (bug, feature request, documentation change, and other).  Each time I submitted, I did receive an email with my responses.  The only thing I cannot test is if the feedback is being submitted correctly to APT (I assume you all can check to make sure you have feedback notifications from my email - bwb0013@uah.edu).

I am a little confused by choosing to report as "other" (see below).  

![feedback_test](https://user-images.githubusercontent.com/56319064/199730216-51328c09-fce3-4f53-b2d4-b03647a46e19.jpeg)

This is what I see when I click to the next page after selecting "other." Where is a user supposed to add details to their issue/concern/thoughts? Or is a user only supposed to add their issues/concerns on the first page when they select the radio button of "other?" (first image that currently states "This is a feedback module test.")

![feedback_test2](https://user-images.githubusercontent.com/56319064/199730785-28e77d3f-d59b-4577-ba53-2afaf0cc5cdc.jpeg)

**Comment by wrynearson** [comment]
Thanks for your quick review @bwbaker1. The "collection" of the feedback will go to @deborahUAH , so I think the points you listed are all on the Google Form side. Once approved, we can push the functionality to Prod, and then any updates you want to make to the form wouldn't need further work from us. Or, we can wait until the form is finalized – up to you.

**Comment by bwbaker1** [comment]
@wrynearson I think my one comment is very insignificant at this point - just needs to be addressed eventually.  My opinion is that this is ready to be pushed to PROD asap since we have several scientists already using the tool.  Just need @deborahUAH to review and give the go ahead.

**Comment by deborahUAH** [comment]
@bwbaker1 I can see your test responses.  Every response to the form submitted ends up in the[ associated spreadsheet](https://docs.google.com/spreadsheets/d/1QKa0y9RcHeDBNmZM2e5u-d0JgvZFSb32mR5nLcIDUVI/edit#gid=406282297).  I have fixed the error in the form for the "other" option.  It has a long form response box now.  My error when building the form.

I suggest you set yourself to be notified when the sheet changes.  I did yesterday and I did get emails today from each of your tests.  

@wrynearson @naomatheus  in my opinion it can go to PROD.  THanks!

**Comment by deborahUAH** [comment]
@naomatheus  did this go to production?  Doesn't look like it?

**Comment by naomatheus** [comment]
@deborahUAH  The PR that resolved this issue is on the way to Prod. Once merge is approved, it will deploy ( tagged colleague in my timezone so this can happen soon). cc @wrynearson

**Comment by naomatheus** [comment]
@deborahUAH  Successfully merged to Prod cc @wrynearson

**Comment by wrynearson** [comment]
Looks good @naomatheus , thanks. @deborahUAH , I filled in a response to test that it's working – looks good to me.

**Comment by deborahUAH** [comment]
@wrynearson @naomatheus  I received email of your test and agree that the form is working in prod.  I will close this ticket. Thanks for getting this implemented.  We may need to readdress the issue eventually when moving to ESDIS operation if google form is not ok to use.  THanks all!
