### ISSUE TITLE
Create landing page to redirect users from impact.earthdata.nasa.gov/apt to earthdata.nasa.gov/apt

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#578]
Currently, [impact.earthdata.nasa.gov/apt/](https://impact.earthdata.nasa.gov/apt/) doesn't work. This has been discussed previously.

The best, easiest solution seems to be to have [https://impact.earthdata.nasa.gov/apt/](https://impact.earthdata.nasa.gov/apt/) point to landing page that says something like:

> ### APT — The Algorithm Publication Tool
> APT has moved to a new URL: [earthdata.nasa.gov/apt](https://earthdata.nasa.gov/apt). You will be redirected in 3 seconds.

## Success Criteria
- [ ] As an APT user, I am greeted with a nice, simple landing page when I go to [impact.earthdata.nasa.gov/apt/](https://impact.earthdata.nasa.gov/apt/)
- [ ] As an APT user, I am automatically redirected to [earthdata.nasa.gov/apt/](https://earthdata.nasa.gov/apt/) after a few seconds.

**Comment by wrynearson** [comment]
cc: @naomatheus @leothomas @aboydnw

**Comment by naomatheus** [comment]
[Branch](https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/add-redirect-for-mcp/app/index.html) to be pushed to MCP S3 bucket for https://impact.earthdata.nasa.gov/apt/

**Comment by wrynearson** [comment]
Hey @naomatheus, I just saw a screenshot of this locally (thanks @TimMcCauley).

Could you re-do the layout to match the following? Sorry if I wasn't clear. Please match the following :)

<img width="1439" alt="Screenshot 2022-09-16 at 14 17 38" src="https://user-images.githubusercontent.com/25919630/190638726-a4812491-397b-4516-9c0a-cda09ec89057.png">

Let me know if you have any questions.

**Comment by wrynearson** [comment]
@naomatheus, I just went to the old url `https://impact.earthdata.nasa.gov/apt/`. The redirect functionality no longer works. I am shown the previous "loading" splash page, which I am stuck on.

Could you look into this to see if this is related to the recent Prod deployment, and let me know if you can fix this?

**Comment by wrynearson** [comment]
Hey @naomatheus, just flagging this ticket. It seems to still be an issue.

**Comment by deborahUAH** [comment]
This issue still exists - users are abandoned at impact.earthdata.nasa.gov/apt (no redirect, no information about new URL).  With web unification the impact.earthdata.nasa.gov/apt site will go away.  Until then, users should get the new address.

**Comment by wrynearson** [comment]
@naomatheus flagging this again for your attention. Please let me know if you're not able to address this during this sprint. cc @batpad

**Comment by naomatheus** [comment]
I'm on it. I'll need to contact Shawn F since we do not have access to the DNS settings that point to the resources. @wrynearson

**Comment by naomatheus** [comment]
Update on this request.
I'll need permissions from MCP administrator to apply a public accessibility policy. I will update when that request can be completed. 
cc @wrynearson

**Comment by naomatheus** [comment]
update on this.
A ticket has been submitted to MCP to apply the necessary policy so that users can visit the redirect from any web browser.

**Comment by naomatheus** [comment]
update on this. Request to apply policy was approved. 
Point of Contact says "it could be end of day today or tomorrow for a safer expectation."
cc: @wrynearson

**Comment by naomatheus** [comment]
Still waiting for this policy to be added. Escalating again. cc: @wrynearson

**Comment by bwbaker1** [comment]
@wrynearson Is there anything I can do to help with this holdup?

**Comment by wrynearson** [comment]
Thanks @bwbaker1, let's see if @naomatheus has any updates or has ideas for how you could help

**Comment by naomatheus** [comment]
Hey @wrynearson @bwbaker1 
This S3 policy is now in place, and we'll be able to wrap up this issue. 
The DNS for impact.earthdata.nasa.gov/apt is managed by a third party, so I believe we can escalate this internally with Shawn F. I'll tag you in channel as well about this.

**Comment by xhagrg** [comment]
@michaelsfoley can we expedite this?

**Comment by bwbaker1** [comment]
@michaelsfoley Do you have any updates on this?

**Comment by wrynearson** [comment]
@bwbaker1 this is still blocked.
