### ISSUE TITLE
Some images do not show in downloaded PDFs.

### ISSUE THREAD

**Issue by naomatheus** [NASA-IMPACT/nasa-apt#593]
Description:
- Some images are not showing journal PDF downloads, even though they are present in the ATBD's user input.
- This may have emerged when resolving the PDF download issue.
- I discussed where to address this issue with @leothomas. The logic lives:
- [here](https://github.com/NASA-IMPACT/nasa-apt/blob/4a382ec9e9b8da70e1318bc26bebdb62091ca675/app/pdf/generator.py#L445) and [here in `process`](https://github.com/NASA-IMPACT/nasa-apt/blob/4a382ec9e9b8da70e1318bc26bebdb62091ca675/app/pdf/generator.py#L371)

Tasks:
- Ensure that `imageBlockNode` type is added properly to documents when they are passed to Latex PDF generator.

Acceptance Criteria:
- Any images can be added to an ATBD. The image will be displayed in the correct position.

**Comment by wrynearson** [comment]
Thanks for raising this @naomatheus. Do you have a sense of the rate of failure for this but? I.e., does every image fail to display, or half, or 1 in 10?

**Comment by naomatheus** [comment]
@wrynearson  from my side it was 4/5 images. Some sections allowed, but the specific section seemed not to be the issue. The image addition/image placement logic needs a general review.

**Comment by deborahUAH** [comment]
@naomatheus @wrynearson I tested PDF download in staging today and added 2 images to the document before downloading.  Both images did not show up in the PDFs (both journal and regular PDF generate).  See PDF ticket for examples #545

**Comment by naomatheus** [comment]
Hey @wrynearson 
This is an older one that I believe can be closed for now.

**Comment by deborahUAH** [comment]
@wrynearson is this type of problem fixed with new approach to PDFs?  I will close if you can affirm.

**Comment by wrynearson** [comment]
Yes @deborahUAH , this is fixed and should be closed. Thanks @naomatheus
