### ISSUE TITLE
Document lock isn't cleared when user leaves edit mode

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#594]
The document lock should be cleared when the user is no longer editing the report. However, we heard from a user that this is not the case. Two users tested editing the same report, and also viewing the same report. They said:

> Caroline and I tested both options. When she was in the document in "Viewing" mode and when she was not logged in the ATP tool. In both cases we got the warning.

I'm not sure how the second scenario is possible because users can only see published documents when they're not logged in. I assume they are using [production](https://www.earthdata.nasa.gov/apt/)?

We should investigate why the report locks are not being cleared.

**Comment by wrynearson** [comment]
FYI @naomatheus

**Comment by deborahUAH** [comment]
Adding this issue as P2 fix to FY23.2.3.   @bwbaker1 use Camille or Ashley to test this and better describe the issue so we know status and can add to next sprint

**Comment by wrynearson** [comment]
Hi @bwbaker1, this should be fixed now. It's ready for your review (which would probably involve two people trying to edit the same document).

I recorded a video of what I tested https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/464#pullrequestreview-1405482597. Please note that if users are trying to edit the document at the exact same time, this fix might not work because we are not forcing page refreshes on users.

If user 1 goes to edit, then user 2 goes to view the document, then user 2 tries to edit, the fix will work. If both users are already on view mode and both try to edit around the same time, this fix won't work.

**Comment by bwbaker1** [comment]
@wrynearson Excellent. Will test asap and let you know how it goes.

**Comment by bwbaker1** [comment]
@wrynearson We tested this and could not reproduce the original error. This is ready for production.
Could we change the color of the warning message box to red? Just to make it stand out a bit more.

**Comment by wrynearson** [comment]
@bwbaker1 I would suggest that we keep the design language the same for prompts, for similar reasons [that we discussed](https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/403#issuecomment-1506831613) for toasts (messages in the bottom right corner).

**Comment by bwbaker1** [comment]
@wrynearson ⬆️ okay. There was a little concern when we were testing this that some users may click through the warning without reading it. I think that is a low risk though. This issue is ready for production. Thanks for the feedback.

**Comment by wrynearson** [comment]
Thanks @bwbaker1. If we get user feedback that they're not acknowledging the warning, we can reassess
