### ISSUE TITLE
BibTeX Import Issues

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#602]
@wrynearson @naomatheus Also see #[601](url)

### Description: 
A couple of reference fields are not populating with BibTeX imports.  The is includes the Journal title and publication year. This is an issue even after using a BibTeX file cleaner. 

### Tasks:
- [x] The journal title and publication year from a BibTeX file should populate.  

### Acceptance Criteria: 
- [x] All included fields in each reference should populate. 

Fields/structure of a reference in the BibTeX file:

![Image](https://user-images.githubusercontent.com/56319064/208710085-8aa24113-e8c2-4a42-a1ec-9a1d415e8f21.png)

How the import looks in APT:

![Image](https://user-images.githubusercontent.com/56319064/208710700-0e742b63-aa19-41d7-b5a0-c4b8119441a6.png)

**Comment by wrynearson** [comment]
@sunu will confirm that this is a frontend issue. If it's self contained, he can own this ticket.

**Comment by wrynearson** [comment]
Hi @bwbaker1, I'm reviewing our teams work on this now. To confirm, are the following issues the correct ones to check for?
- The `Title` field has many curly brackets (`{` and `}`) which shouldn't be there
- The .bib value for  `journal` should fill in the `Series` field
- The .bib value for `year` should fill in the `Year` field

**Comment by wrynearson** [comment]
I've made a .bib file to match the screenshot you provided.

![Image](https://user-images.githubusercontent.com/25919630/222167563-f75a4307-3b49-42fd-9f58-c884a1a9f2fc.png)

With our fix, this is now imported as the following:

![Image](https://user-images.githubusercontent.com/25919630/222167780-0dfd1769-c08e-47d7-9fb5-1efdfc0a6c67.png)

**Comment by bwbaker1** [comment]
@wrynearson Yes that is correct regarding the journal series and year.  

However, I think the curly brackets in the title results in the first letter of those specific words (in brackets) being capitalized in html/pdf.  In your example, does the title appear in html/pdf as "AGU to Launch a New Open-Access" or is it "Agu to launch a new open-access"?

**Comment by wrynearson** [comment]
> does the title appear in html/pdf as "AGU to Launch a New Open-Access" or is it "Agu to launch a new open-access"?

@bwbaker1 it's capitalized:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/25919630/222200308-24636088-a1f6-438b-84f6-d06762e0d446.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/25919630/222200517-bbce9f0d-ff93-4416-be38-103b53f17af5.png">

I'll merge this PR and then you and the team can test this on staging

**Comment by wrynearson** [comment]
@bwbaker1 this is on staging and is ready for you and the team's review. cc @cw0045 @deborahUAH

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH This has been tested.  All of the fields are populating correctly now.  The only issues I found were that (1) the journal title and volume number should be in italics and (2) only proper nouns should be capitalized in the title.  

If the first issue is a relatively big fix, I would suggest going ahead and pushing the bibtex import fix to PROD and then creating a separate issue for the italics formatting (unless this would create a problem). My reasoning is that it would be very helpful for our current users to be able to import references. 

@ashleyriddle92 @cw0045 The capitalization issue just needs to be noted in the user guide (and maybe in the text prompt) to inform users that they must ensure that only proper nouns are capitalized.

**Comment by wrynearson** [comment]
Thanks for the quick review @bwbaker1.

I think the first issue you mention (italics) should be a separate issue, because it is not directly driven by the importation of a BibTex file – instead, it's how we're styling the information once it's imported.

Let's ask @sunu if he thinks the 2nd issue (capitalizing) can be easily fixed during importation. I would guess that that is also better dealt with a separate, styling-driven ticket. This could be more tricky than it sounds to identify proper nouns (This `and` That vs. This `And` That, if that's what you mean).

Regardless, I agree that we should push this to production and then address these two issues.

**Comment by bwbaker1** [comment]
@wrynearson Sounds good.  The second issue is actually more complicated because APA reference format only capitalizes proper nouns (e.g., United States, Earth, St. John's River, etc.).  I think it is best if we just note this in the user guide and text prompts for users. I believe users may be able to use a BibTex APA template for this.

**Comment by wrynearson** [comment]
Ah OK, I misunderstood. I think that is something that is much better solved with user guidance than a technical solution 😄

**Comment by bwbaker1** [comment]
I believe this ticket is done. It just needs to be pushed to PROD.

**Comment by wrynearson** [comment]
Thanks @bwbaker1, tagging @naomatheus to push this when you have the chance.
