### ISSUE TITLE
Multiple paragraphs show up as one paragraph

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#603]
@wrynearson @naomatheus 

### Description: 
For each document section, multiple paragraphs display as one continuous paragraph.

### Tasks:
- [ ] A line break needs to be added between each paragraph.

### Acceptance Criteria: 
- [ ] Multiple paragraphs are separated in the PDF downloads.

Two separate paragraphs in APT:

![Image](https://user-images.githubusercontent.com/56319064/208714602-8afd5afe-b799-4475-adf2-b8780b3d623f.png)

Result in the PDF.  Note it is one continuous paragraph.

![Image](https://user-images.githubusercontent.com/56319064/208714963-438ace0a-63fe-496a-9164-a5413dc45749.png)

**Comment by wrynearson** [comment]
I'm pretty sure we had this issue in SNWG. @thenav56 and @frozenhelium, this required adding line break support in both the frontend and backend, if I remember correctly. cc: @batpad
