### ISSUE TITLE
Content in sections/subsection don't always show up

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#604]
@wrynearson @naomatheus 

### Description: 
Content does not always show up for sections and subsections.  After some testing, this issue may be related to adding reference(s). 

### Tasks:
- [x] Determine what is causing this issue.

### Acceptance Criteria: 
- [ ] All added content displays in the PDF documents. 

Note two references at the end of the paragraph.

![Image](https://user-images.githubusercontent.com/56319064/208717073-15cfd526-c3b3-4280-a0e2-50441ba6c8ae.png)

PDF of same section after adding multiple references.

![Image](https://user-images.githubusercontent.com/56319064/208717442-43c71ee9-05da-4d58-a1aa-86e19e8263b8.png)

**Comment by wrynearson** [comment]
@bwbaker1 are you noticing this content disappearing on the frontend in view mode as well as in the PDFs, or just in the PDFs?

**Comment by bwbaker1** [comment]
@wrynearson All of the content shows up while in view mode. It disappears only in the PDFs.  I think adding a reference is somehow the issue.  Also, if more than one reference is added, only the first appears in the PDF. See screenshots below.

### **Content disappearing example**
Editing mode: 
Introduction: Text but no reference. Historical Perspective: Text and reference.
![Screen Shot 2023-01-10 at 8 03 49 AM](https://user-images.githubusercontent.com/56319064/211572231-65dc80c2-faa6-4d6b-a72e-50261ec4538f.png)

Viewing mode:
Note text and reference appear correctly.

![Screen Shot 2023-01-10 at 8 04 25 AM](https://user-images.githubusercontent.com/56319064/211572339-0f311a1a-ab28-4171-a72f-399f2ce3cca5.png)

PDF:
Introduction: Text appears.  Historical Perspective: Text does NOT appear but the reference does.  

![Screen Shot 2023-01-10 at 8 04 54 AM](https://user-images.githubusercontent.com/56319064/211572722-229d25e0-6d3f-407a-9829-8083def45fa3.png)

### **Adding two references example**
Editing mode:
Add two references.

![Screen Shot 2023-01-10 at 8 12 55 AM](https://user-images.githubusercontent.com/56319064/211574106-99fee43c-351d-46ff-9bcd-14fac530b1e9.png)

Viewing mode:
Both references appear.

![Screen Shot 2023-01-10 at 8 12 37 AM](https://user-images.githubusercontent.com/56319064/211574215-dc995a97-d4ea-426f-a179-aa3a75b97271.png)

PDF:
Only the first reference appears.

![Screen Shot 2023-01-10 at 8 13 28 AM](https://user-images.githubusercontent.com/56319064/211574342-3c85af21-a10b-4123-aad6-fa96fd5f9360.png)

**Comment by naomatheus** [comment]
**Determine what is causing this issue.**
Issue was caused by logic in `app/pdf_utils/fill_sections.py` that has been updated to get all references and associated text.

**Comment by naomatheus** [comment]
This will be ready to test in staging when [PR 605](https://github.com/NASA-IMPACT/nasa-apt/pull/605) is approved.

**Comment by naomatheus** [comment]
This PR will be reviewed soon @bwbaker1 , this will cover #606  in the same PR.

**Comment by wrynearson** [comment]
With the new PDF architecture, this issue is fixed.
