### ISSUE TITLE
Warn users that figure caption is required

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#613]
@wrynearson @naomatheus @deborahUAH 

### Description: 
All figures should include a caption created by the user.  To ensure this happens, a warning message is needed to tell users that a figure caption is required. 

### Tasks:
- [x] Provide the user with a warning message when an image (figure) is added without a caption.  This warning should be triggered for both PDF types. This warning should state "A figure caption is required." 

### Acceptance Criteria: 
- [x] A warning appears when a user adds an image but no caption (need to determine when this warning should occur).

###Example:

![Image](https://user-images.githubusercontent.com/56319064/211329752-ccaa1822-b4e9-42ed-b3f3-0438b6401144.png)

**Comment by wrynearson** [comment]
@frozenhelium we have many possible ways to implement this (a check at the time of image upload, a check on edit page change, a check on draft -> closed review, etc.
