### ISSUE TITLE
Create a source of truth ATBD

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#619]
### Description: 
Provide DevSeed with an example ATBD with all types of formatting and content (e.g., figures, tables, equations, etc.).

### Tasks:
- [x] Edit the GEDI L4 ATBD to fit all AGU formatting standards (double-check with new standards). 

### Acceptance Criteria: 
- [x] Deliver example ATBD to DevSeed.

**Comment by bwbaker1** [comment]
@wrynearson  Here is an example journal PDF.  I didn't include line numbers (MS Word is a hassle), but the current line numbers in APT work properly. 


[GEDI_ATBD_L4A_BradTest.pdf](https://github.com/NASA-IMPACT/nasa-apt/files/10461603/GEDI_ATBD_L4A_BradTest.pdf)

**Comment by wrynearson** [comment]
Flagging @batpad, @sunu and @frozenhelium for when we start working on the journal PDFs

**Comment by wrynearson** [comment]
@bwbaker1 the example here doesn't include a ToC. Does the Journal PDF need to have a ToC?

**Comment by bwbaker1** [comment]
@wrynearson No, the journal PDF does not need a ToC.
