### ISSUE TITLE
PDF paragraph indentation

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#620]
@wrynearson @naomatheus @deborahUAH 

### Description:
For consistency between journal and general PDFs, all paragraphs should begin with an indented sentence.  Currently, the journal PDF does indent all paragraphs but the general PDF does not. 

### Tasks:
- [x]  Indent the first sentence of each paragraph in the general PDFs (follow the journal PDF format). 

### Acceptance Criteria:
- [x] Document PDFs is consistent in terms of paragraph indentation (with Journal PDF, not updated with this ticket) by indenting the first line of every paragraph

![Image](https://user-images.githubusercontent.com/56319064/211597012-3221ccf4-b4ba-4b41-9406-77f7351d13bb.png)

Journal PDF: Note the first sentence is indented, which is what we want. 

![Image](https://user-images.githubusercontent.com/56319064/211597127-6bcc1868-f265-492e-a57f-afe6e2af8381.png)

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson Looks good.  This is ready for production.

cc @deborahUAH
