### ISSUE TITLE
Spike: Rearchitect PDF styling and generation

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#622]
There are many bugs and small styling changes to be made with PDF generation (tagged with https://github.com/NASA-IMPACT/nasa-apt/labels/PDF). Our current technical approach is finicky, time consuming, and feels a lot like whac-a-mole (if we solve one issue, another comes up).

We would like to investigate changing our PDF styling, formatting and generation approach to one based on HTML. tl;dr, this will mean that any style/format change in the view mode will be present in the PDF export. This will mean that PDF changes take significantly less time.

We are not confident that this approach will work, so @frozenhelium and @sunu will conduct a time-boxed scoping exercise.

**Comment by naomatheus** [comment]
@sunu @frozenhelium Let me know how this is going you guys! Thanks for taking this on

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH I want to make sure we have the correct context for the motivation for generating PDFs. Please let me know if the following are fair to say:
1. The Document PDF's purpose is to export the ATBD in a way that closely matches the style and format of the APT view mode, to allow for general-purpose use outside of APT.
2. The Journal PDF's purpose is to export the ATBD in a specific format and style, for review by academic journals.

I'd also like to confirm that only _visual_ elements of the PDF (how it looks, sections, headers, references, italics, etc.) are important to users, and not _structural_ elements (things we can't see but automated processing of PDFs may notice).

cc: @batpad

**Comment by deborahUAH** [comment]
@batpad @wrynearson  The document PDF is so that users can obtain an ATBD for keeping with data or referring to as needed.  For this reason, it should have all content in a style that is easy to read and understand in a format that is clear - it should have all the parts of the html document - but formatting of those parts should be for maximum reading ease and understanding.  This means references should be unlike the html but more like that of a journal article (name, year) in line and reference list at bottom of doc.

The journal PDF must be in the style needed for AGU ESS journal for submission.  _In a perfect world,_ we would have various journal formats that one could download (i.e. meeting one of Nature or AGU or AMS journal submission requirements).  But I will settle for AGU styling.

I need an example of what is meant by a structural element and what effect it will have on PDF use to better understand your last statement.

**Comment by wrynearson** [comment]
Hi @deborahUAH, thanks for your reply. This is very helpful.

We've concluded that the structural elements aren't a risk for our development, so no need to worry about them. An example would be if an advanced user ran a script to collect metadata on the PDF, or to extract equations in an automated way. If you know of users interacting with ATBDs in this way, let us know, but we imagine this isn't something that's often done.

Our team will first focus on creating a fully functioning Document PDF. This seems like it's more important for users at this point. Once the Document PDF is fully functioning, we will do the same with the Journal PDF.

@sunu will continue his research until early next week (Tuesday), then we will make tickets to capture the implementation plan. Unless we encounter unexpected issues, we're confident with this approach, and we're confident we'll make significant improvements on the Document PDF this sprint (Jan 23 - Feb 3).

**Comment by sunu** [comment]
We considered 2 different tools to render HTML to PDF on the backend.
1. [WeasyPrint](https://github.com/Kozea/WeasyPrint/)
2. [Playwright](https://playwright.dev/python/)

Advantages of WeasyPrint:
- It is a pure Python library. Hence, easy to integrate into our workflow
- it has support for table of content generation through the use of [`target-counter` ](https://www.w3.org/TR/css-gcpm-3/#target-counter) and it can support rendering Math equations through Katex.

Downsides of WeasyPrint:
- it has a custom CSS rendering engine which may not keep up with web standards
- it doesn't have a JS engine. So the input needs to be pre-rendered html without any dependency on Javascript
- weasyprint is predominantly maintained by a single author

Advantages of Playwright:
- It's a tool by Microsoft. Very robust and well-maintained. Allows using webkit, chromium or firefox in headless mode through an easy to use api
- Manages its own headless browser installation
- Supports rendering CSS, JS through webkit
- Natively supports MathML to render math equations

Downsides of Playwright:
- Browsers haven't implemented `target-counter` yet. So Playwright doesn't support that either.
	- But we can use an external library like [pagedjs](https://github.com/pagedjs/pagedjs) to add support for generating table of contents
	- Useful example repo on using pagedjs: https://github.com/ashok-khanna/pdf

I believe Playwright combined with PagedJS covers all the features we need to make Document PDF export work.
cc @batpad @wrynearson @xhagrg

**Comment by wrynearson** [comment]
Thanks @sunu for your investigation and write up! Let's go ahead with Playwright + PagedJS

**Comment by sunu** [comment]
Next steps on integrating Playwright + PagedJS into the PDF export workflow:
- We'll integrate PDF generation through Playwright as a background job implemented through FastAPI background job in dev environment and as a lambda listening to a SQS queue in AWS environment.
- The background job will generate the PDF by visiting a page through webkit and rendering that into a PDF. See https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/405 for more details.
- The PDF will be saved to S3. The path of the PDF, the requesting user and an uuid will be saved to Postgres for future retrieval.
- We'll add an api endpoint to check whether a particular PDF is ready for download on not by using the related UUID. The frontend can use this endpoint to poll for the status of the requested PDF.

**Comment by frozenhelium** [comment]
@sunu I've created a new view to preview the document, more details on: https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/407

**Comment by wrynearson** [comment]
@xhagrg @deborahUAH @bwbaker1 we have the first pass of the PDF change on staging. You can access it by adding `/pdf-preview` to any ATBD that you have access to on staging.

For example, for the document https://nasa-apt.surge.sh/documents/wills-test-atbd/v1.0/, the link to access the PDF preview from https://nasa-apt.surge.sh/documents/wills-test-atbd/v1.0/pdf-preview.

Table of contents and correct page breaks are in the works, as are smaller styling tweaks we can make. We will also remove the "scroll bars" that appear next to the image and table. This preview shows the stability of PDF generation, images, rich text, equations, and more.

[Here is an example](https://github.com/NASA-IMPACT/nasa-apt/files/10570926/APT-will-ATBD.pdf) we generated a few hours ago.

**Comment by bwbaker1** [comment]
@wrynearson Great! Will start testing asap.

**Comment by wrynearson** [comment]
I will close this ticket because we have determined the approach for implementing this ticket. We can make new tickets for further implementation if necessary.

**Comment by bwbaker1** [comment]
@wrynearson  I tested PDF download and section order using Chrome, Safari, and Mozilla. All of these seem correct.  

@deborahUAH Based on our ATBD template, do we want to reorder and move section 5 (Algorithm Availability) to just above section 8 (Data Access)? It would then become:

5 Algorithm Usage Constraints
6 Performance Assessment Validation Methods
7 Algorithm Availability
8 Data Access

Current section order:


![Image](https://user-images.githubusercontent.com/56319064/217070601-e85e56a9-e37b-4f0e-8a69-e994a1d504cc.png)

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this is now live on staging.

If you click on any document on staging, and click on download > document.pdf, the correct document PDF will now download. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25919630/221208348-2783f8e3-842c-42b4-bc63-056df624f8d9.png">

There were quite a few "under-the-hood" changes that needed to be made to get this functionality to work. Please note that this only covers document PDFs – journal PDFs will come later.

Feel free to review this, but you've already seen the end result when you added `/pdf-preview` to the document URL. 

Once you approve this change _and_ you approve the styling changes that will be ready by mid-next week, we can push them all to production. Alternatively, if you'd like users to be able to download PDFs on production now (without the table of contents, in-line references, or other styling changes), we can push this earlier, but I don't recommend it.

cc @sunu @batpad
