### ISSUE TITLE
The user should have the role they’re assigned displayed underneath their username on the home screen.

### ISSUE THREAD

**Issue by ashleyriddle92** [NASA-IMPACT/nasa-apt#630]
The user's role (contributor, reviewer, etc) should be displayed under their username in the header.

**Comment by ashleyriddle92** [comment]
![Image](https://user-images.githubusercontent.com/109154098/215597919-dc1664d9-d066-47ab-a6c8-d1e122013320.png)

**Comment by wrynearson** [comment]
Good idea @ashleyriddle92  – I've had that issue on SNWG (forgetting which role I have, for testing purposes).

We could default to contributor (as that's a doc-specific role) unless the user has the `reviewer` properties in Cognito.

This could be visualized in a few ways:

1. Immediately below the username in the header (as suggested)
2. Listed in the user dropdown (e.g., replacing the word "Account" for the role, or placing the role to the right)
3. Listed in the user settings (e.g., under the email in a new row, titled "role")

<img width="258" alt="image" src="https://user-images.githubusercontent.com/25919630/215738755-d2957d0e-08cd-4c4d-a07f-7add9d489ea0.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/25919630/215738986-334bb382-3360-42b3-a4ed-b16f8c6683b5.png">

I think understanding the reason why a user would want to know their role will help us determine how prominently we should display it.

cc: @frozenhelium @batpad

**Comment by ashleyriddle92** [comment]
@wrynearson I think being able to see at a glance what the role is would be helpful, especially for users who may be switching between contributor for one project and reviewer for another. My preference would be for option 1 or 2.

**Comment by bwbaker1** [comment]
@deborahUAH Should this ticket be closed since it is a new feature/additional development?

**Comment by deborahUAH** [comment]
yes.  I think so.  Too much right now with new plan

**Comment by wrynearson** [comment]
@deborahUAH I think we need to discuss this "new plan". Are you referring to allowing to ATBD template use? If so, there's a _lot_ that needs to be scoped out there.

cc @batpad
