### ISSUE TITLE
Documents do not load in staging. Documents cannot be created

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#631]
Documents are not loading in staging, for multiple accounts.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/25919630/215736894-85bee033-333f-4c65-8e1a-5ced3dc1d1ec.png">

In the console, I get `500` errors:
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/25919630/215737202-562e4b32-b411-44ea-af80-a59239463b06.png">

Documents also cannot be created, with the same `500` error.

**Comment by wrynearson** [comment]
Have we seen this issue before? cc: @batpad

**Comment by naomatheus** [comment]
Hey @sunu 
I have identified the issue. I'll post the stack trace in our Slack channel. You can also view that here in the AWS account within this cloudwatch log group and stream. 

log group : redacted
log stream: [2023/01/31/[$LATEST]82c99d447335404d8cf45505bd2b282d]

**Comment by naomatheus** [comment]
This appears resolved. However, please confirm. @wrynearson @sunu 
I was testing with the `curator@apt.com` user who previously did also see the error and now does not see the error.  ATBD documents load on the Dashboard screen.

**Comment by naomatheus** [comment]
Could logic be added here to check for the `preferred_username` attribute? and replace it with an alternative?
https://github.com/NASA-IMPACT/nasa-apt/blob/78e1b06c30a01e025a31c8a8d8c675a2cc57c3b3/app/schemas/users.py#L33

**Comment by wrynearson** [comment]
Thanks @naomatheus, this is resolved. For clarity, this issue occurred if a user doesn't have a `preferred_username` attribute. I had manually created an account for @xhagrg in Cognito, where the "create user" workflow does not ask for `preferred_username`, thus causing the issue. @naomatheus was able to add a `preferred username`.

I'll close this for now, but we should think of a fail-safe to always populate the `preferred_username` field.

**Comment by naomatheus** [comment]
If we create the CognitoUser class always with a preferred_username that's just a generated string, then if someone actually enters one it would be replaced by _unpack_attributes. 

```python

class CognitoUser(AnonymousUser):
    """User contributing to an ATBD Version, as returned by Cognito"""

    sub: str
    email: str
    cognito_groups: List[str] = Field([], alias="cognito:groups")
    preferred_username: str = None

    def __init__(self, values):
        self.preferred_username = self.generate_username()
        self._unpack_attributes(values)

    @root_validator(pre=True)
    def _unpack_attributes(cls, values):
        # list_users_in_group response model has user attributes
        # under `Attributes` whereas the admin_get_user response model
        # lists user attributes under `UserAttributes`. The following
        # line searches through the provided values, searching for
        # either the `Attribuets` or the `UserAttributes` key to then
        # use to reformat the values of the data model.

        user_attributes_key = next(
            (k for k in values.keys() if k in ["Attributes", "UserAttributes"]), None
        )

        if not user_attributes_key:
            return values

        for attribute in values[user_attributes_key]:
            if attribute["Name"] in [
                "email",
                "sub",
                "preferred_username",
            ]:
                setattr(self, attribute["Name"], attribute["Value"])
        return values

    def generate_username(self):
        random_str = ''.join(random.choices(string.ascii_letters + string.digits, k=5))
        return f"anon_{random_str}"


```

**Comment by xhagrg** [comment]
RGT had similar issues and Tim had a fix in place. Might be beneficial to go through RGT changes to handle similar issue.

**Comment by xhagrg** [comment]
I believe the email address was used to populate the preferred_username when the information was missing.
