### ISSUE TITLE
Add a separate Edit button for users to utilize when they need to edit an unfinished ATBD

### ISSUE THREAD

**Issue by cw0045** [NASA-IMPACT/nasa-apt#632]
As it currently stands, users have to click on a drop-down menu on the APT UI in order to access the edit option when working on unfinished ATBDs (see screenshot). We recommend having a separate button at the top of the section that is placed before the "Request Review" button for easy access to editing functions. 

![Image](https://user-images.githubusercontent.com/57103816/215879277-1ac187ac-7d0f-4992-932f-4c91574e6791.png)

**Comment by wrynearson** [comment]
We recently implemented the same feature on SNWG:

Document `view` mode
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/25919630/215991842-17a6596e-89e9-461d-b405-fbc120ec5792.png">

Document `edit` mode
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/25919630/215991927-f70b1136-6321-44d4-8c4b-7649428b7c31.png">

Dashboard
<img width="1683" alt="image" src="https://user-images.githubusercontent.com/25919630/215992105-4995e710-0ad4-4f92-ab0f-ee625d55c75e.png">

Do the positions and text look good to you @cw0045?

**Comment by cw0045** [comment]
Yes, this is exactly what we were thinking! :) @wrynearson

**Comment by bwbaker1** [comment]
@deborahUAH Though this would be a nice feature, should we close this ticket since it is new development?

**Comment by deborahUAH** [comment]
Keep this one.  I would think it could be easily done and the value is worth it.

**Comment by wrynearson** [comment]
Yep, this will be a quick enhancement.

**Comment by wrynearson** [comment]
@bwbaker1 @cw0045 @deborahUAH this is on staging and is ready for your review.

We've added the functionality in the first and third screenshots ☝️. We didn't add the `Exit editing` button because it wasn't fitting well next to the step counter. I suggest that we push this to production and, if we get feedback from multiple users that the `exit editing` flow is confusing, then we come back and reassess.

**Comment by bwbaker1** [comment]
@wrynearson This is a nice addition. I especially like the ability to enter edit mode from the dashboard (screenshot 3). I am a little concerned that the exit editing flow will be confusing to new users, but I agree to go ahead and push to production and wait for feedback. We will note this in the user guide and our creating a document video to try and reduce any confusion.
