### ISSUE TITLE
Implement a mechanism to authenticate as machine user

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt#633]
As part of the new PDF generation process described in https://github.com/NASA-IMPACT/nasa-apt/issues/622#issuecomment-1409773596, a headless browser needs to authenticate on the backend's behalf to access document view of an ATBD and convert that to a PDF.

Currently we only have support for authenticating through Cognito and that complicates this workflow quite a bit; especially in the docker based development environment. This process will be even more complicated once we add mandatory 2FA into the mix. 

Alternatively, we can add support for authenticating through an api key/machine key for this particular workflow. Some notes on how this could work:
- For the ATBD data endpoint, the backend api will optionally accept a machine key
- The frontend will accept a machine key as query parameter for the document view and inject it into the corresponding api call for authentication

Another possible alternative is to
- Inject the machine key into the headless browser's localStorage.
- The frontend will then send this machine key as a Bearer Token auth header and the backend will check the auth header for this machine key.

@frozenhelium Can you confirm whether the frontend currently stores the bearer token in localStorage?

**Comment by batpad** [comment]
Just to update this ticket based on conversation:

We can **probably** avoid this additional machine key authentication on the backend, by having the backend pass in the bearer token that it receives from the user on the `/print_pdf` endpoint, to the headless browser instance, where we just put that same token in localStorage for the headless browser to authenticate.

This approach should work, in which case we won't need to implement a machine user key.

**Comment by frozenhelium** [comment]
@sunu These are the values we store in the client side
![2023-02-03-181008](https://user-images.githubusercontent.com/4931541/216603575-6cb9afcc-441e-482e-b044-5de3a7ab0fdf.png)
and also
![2023-02-03-181423](https://user-images.githubusercontent.com/4931541/216604009-1bc1d2cf-f3b2-4809-b602-76966d734696.png)

**Comment by sunu** [comment]
We ended up setting the following values in localStorage of the headless browser to authenticate successfully:
```python
    "localStorage": [
        {
            "name": f"CognitoIdentityServiceProvider.{config.APP_CLIENT_ID}.LastAuthUser",
            "value": user_email,
        },
        {
            "name": f"CognitoIdentityServiceProvider.{config.APP_CLIENT_ID}.{user_email}.accessToken",
            "value": access_token,
        },
        {
            "name": f"CognitoIdentityServiceProvider.{config.APP_CLIENT_ID}.{user_email}.idToken",
            "value": id_token,
        },
    ],
```
side note: the UI still requires access to Cognito to fetch user data (eg: user name) when required.
