### ISSUE TITLE
Email notifications not working for thread mentions

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#636]
From #370.

Emails are not being sent to users mentioned in comments. Investigate this when we implement other email notification text and functionality.

**Comment by wrynearson** [comment]
@thenav56 This could be a good first issue for email notifications. #456 that we have implemented should be sending email notifications, but isn't.

[Here's the same ticket](https://github.com/NASA-IMPACT/snwg-script-project/issues/184) for SNWG, and the [main PR](https://github.com/NASA-IMPACT/snwg-backend/pull/104).

**Comment by wrynearson** [comment]
@bwbaker1 this is live on staging. I wrote the following as `contributor@apt.com` and mentioned `will@developmentseed.org`:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/25919630/220298920-6a3756fe-fd10-4898-abd1-e8f8db572a15.png">

I received the following emails. The first was for a thread being created on a document that `will@developmentseed.org` is a contributor of:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/25919630/220299031-3afd7887-1f4a-4715-a902-bcf485d04e98.png">

The second was for being mentioned in the same thread:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/25919630/220299327-d1e2f2ec-05ec-443d-9806-f4d96af34cd4.png">

Is this duplication desirable? If not, I suggest that we should change the expected behavior so that only mentioned users receive emails in threads (and not all contributors as mentioned in lines 22 and 23 of the [events document](https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/edit#gid=0))

@thenav56 please note that the ATBD title is not being parsed correctly in email notifications for thread mentions (in the last screenshot ☝️)

cc @batpad @sunu

**Comment by wrynearson** [comment]
Update: the ATBD title issue is now fixed. I will leave this ticket in review until @bwbaker1 and @deborahUAH approve for us to merge it to production.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH @cw0045 @ashleyriddle92 We tested thread mentions and found some issues with the notifications. Our testing results are [here](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit#gid=1371486832).

**Comment by wrynearson** [comment]
I've fixed the first issue (text changes). I'll wait for @thenav56 to look at the functionality ones (resolving comments not sending emails), and then we can re-review this ticket before closing it

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH these issues ☝️ have been addressed. Tomorrow I'll merge in a change to add intro text to a few emails ("Hi $preferred_username, ...")

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH We re-tested these fixes and things are working properly now. I think this issue can be closed and pushed to production.

**Comment by wrynearson** [comment]
@naomatheus – can you help us push this to production when you have the change?

**Comment by naomatheus** [comment]
Hey @wrynearson 
I am blocked on deploying to production. I am currently working on a resolution with Shawn F.

**Comment by naomatheus** [comment]
Update: @wrynearson Issue 1 with Shawn F is resolved. 
I need some comments from @sunu  regarding Latex/Libtex libraries and how they might be safely removed so as not to block deployment.

**Comment by wrynearson** [comment]
FWIW, this ticket wasn't blocked by https://github.com/NASA-IMPACT/nasa-apt/issues/636#issuecomment-1468984263
