### ISSUE TITLE
Initial styling changes for document PDF

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#642]
After implementing #622 architecture, we will need to edit the styling to better reflect the style and format needed for document PDFs.

The overall goal is to **give users the ability to export their work from APT into a sharable file format (PDF)** to share with colleagues outside of APT. While APT would probably desire that viewing and sharing be done within the platform to increase usage, the reality of the ATBD world is that PDFs are still a dominate file format for sharing information.

To achieve this goal, the new document PDFs match the styling of the `view` mode as closely as possible. Our new approach of PDF generation will help with this immensely.

The immediate work on this ticket will include:

- [x] Adding a table of contents section
- [x] Removing page breaks
- [x] Ensuring line breaks are consistent between sections, headers, etc.
- [x] _Potentially_ other styling tweaks requested by the APT team or users (e.g., page numbers, header sizes, fonts, etc.)

**Comment by wrynearson** [comment]
I wrote a ticket to capture the initial styling changes that we should make ASAP, and definitely within this sprint. cc @batpad @frozenhelium @sunu @deborahUAH @bwbaker1

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this is ready for your review on staging. We have implemented the table of contents, line breaks, and other standard styling. At this point, I think we can call document PDFs fully functioning and usable by users.

**Comment by wrynearson** [comment]
Here's an [example PDF](https://github.com/NASA-IMPACT/nasa-apt/files/10872619/wills-test-atbd-vv1.0.4.pdf). Note that it is intentionally "stress tested", so a very long equation and very large number of indents both overflow off of the PDF

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH @cw0045 @ashleyriddle92 We will test asap.

**Comment by wrynearson** [comment]
I'm marking this as `Ready for Production Deployment` because it's being addressed in other tickets that are approved by the APT team. cc @bwbaker1
