### ISSUE TITLE
Ensuring inline citations are displayed correctly

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#646]
Make sure that Document PDF references are displayed in a functional way.

## Acceptance Criteria
- [ ] Replace superscript numbers with (author, year) notation for in-line citations.
- [ ] Link from in-line to bibliography
- [ ] If straightforward, link from bibliography to in-line

**Comment by wrynearson** [comment]
Hey @bwbaker1, this ticket is meant to outline work related to references in the Document PDF. Right now, we're displaying in-line citations as simply a superscript of the reference number. For example:

PDF:
![Image](https://user-images.githubusercontent.com/25919630/222697191-71f3497c-71a8-4f15-9c90-463b89b2469f.png)

This is the same as the view mode, but without the tooltip:
![Image](https://user-images.githubusercontent.com/25919630/222697329-f37daa5b-984b-4677-98b8-321c5ed00aad.png)

We're currently thinking of adding in cross linking between the in-line citation and the reference section – clicking on the in-line citation would bring you to the reference section, and clicking on the reference would bring you to where it's located. 

We'll investigate to make sure this is standard practice. If the users have any requirements here, please let us know.

cc @batpad

**Comment by bwbaker1** [comment]
@wrynearson @batpad I think linking the in-line and reference sections as you explained would be excellent. This is standard practice for online accessible articles - though I don't recall seeing the linkage from the reference (in ref section) to where it is located in the document.  This would be very useful!

I do want to note that the in-line citation must be (author, year) and not a superscript number. For example: (Doe & Smith, 2023)

**Comment by wrynearson** [comment]
Thanks for the context @bwbaker1 – we can start with in-line -> reference section and then assess reference section -> in-line, and will implement that if it's straightforward.

Good to know about the required format. I was assuming this was just necessary for the Journal PDF, so we'll implement this format (author, year) in the Document PDF.

**Comment by wrynearson** [comment]
Duplicate of #651, closing
