### ISSUE TITLE
Curator dashboard fails gracefully

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#647]
Upstream: https://github.com/NASA-IMPACT/nasa-apt/issues/643#issuecomment-1449747625

We want to change how errors are handled in the curator dashboard. From the upstream issue ☝, we want to return reports if certain information (author, etc.) isn't found for some reason, and instead provide a message for users to identify the problem.

**Comment by wrynearson** [comment]
Hey @leothomas, when you have the chance, could you help expand this ticket to capture what you were thinking would be needed here?

**Comment by leothomas** [comment]
## Bug report: 
### Current behaviour:

Anytime a document is retrieved from the database it only contains user subs (cognito managed uuids) for each of the user related fields:  `owner`, `authors[]`, `reviewers[]`, `created_by` and `last_updated_by` (note that the first three are only applicable to `atbd_versions` and the last two are found in both `atbd_versions` *and* `atbds`. 

The user information itself (name, email, preferred_username, etc) it stored in Cognito. 

When the API loads a document, it looks at the permissions of the person making the request and loads the appropriate information from Cognito. (eg: an author is loading a document that's in closed review, therefore the values of the `name` field for all `reviewers[]` gets replaced by `reviewer #1`, `reviewer #2`, etc. A curator is loading a document, the values of all the user info fields are included in the response. 

### Problematic behaviour:

In this specific case, we encountered an error when one of the user subs (cognito managed uuid) in the `authors[]` array was *not* found in cognito, which made the application fail with an unhandled error, on [this line](https://github.com/NASA-IMPACT/nasa-apt/blob/c2897ea4548597d7f2fd8ddb46c7cdcd8b137ca7/app/users/cognito.py#L93). 

The reason this error is unhandled at the moment is that the API makes the assumption that _any_ user sub within a document will be present in the cognito user pool. This is a reasonably safe assumption given that user subs are entirely managed by the application backend, however, that is clearly not always the case.

## Desired Behaviour: 
We should be handling the error when a user sub from a document is not found in cognito and displaying an error message (eg: `Error: user information not found, please contact system administrator`) for that document, while allowing the rest of the documents to load

**Comment by wrynearson** [comment]
Thank you @leothomas! @thenav56 let us know here if you have any questions regarding this ticket.

**Comment by wrynearson** [comment]
@thenav56 is there something I can test on this ticket, or should we mark this as done/ in review by NASA's side?

**Comment by thenav56** [comment]
We will need to have data from non-existing users. I created some comments and then restarted the container which reset the cognito user-pool making old users dangling. Maybe we can try that.
Or modify the data in the database, basically change the user_sub stored in atbd or atbd_versions user columns.

**Comment by wrynearson** [comment]
Thanks @thenav56 ! Could you do that (resetting the local user-pool) and take some screenshots/screen recording and post them here? I think seeing your flow locally should be sufficient to test this, unless @batpad disagrees

**Comment by thenav56** [comment]
Sure.
I basically modified the DB content with random user_sub. And here is a screenshot.
![2023-03-21-201111](https://user-images.githubusercontent.com/7059255/226637545-b40c8ccd-f900-446f-94c5-c771c89d1d15.png)

**Comment by wrynearson** [comment]
Thanks @thenav56 – this looks good. I wonder if @bwbaker1 or co have thoughts about rewording "Dangling User" to something else, because it's probably not a term users understand? Maybe something like "Deleted User" (although it doesn't necessarily refer to deleted users)?

@thenav56 could you also post a screenshot of the curator dashboard?

**Comment by bwbaker1** [comment]
@wrynearson ☝️ I think "Deleted User" or maybe even "User Not Found."  Either of those will be more informative to the user than "Dangling User."

**Comment by wrynearson** [comment]
OK, @thenav56 let's use "User Not Found" (unless you think "Deleted User" or something else is better).

**Comment by thenav56** [comment]
Sure thing.

Here is the PR with the attached screenshot for the Curator Dashboard.
https://github.com/NASA-IMPACT/nasa-apt/pull/662

**Comment by wrynearson** [comment]
@thenav56 – @sunu and I tested thin on staging. It looks great 👍 

I added a user to a report, and then deleted the user from Cognito. After 30+ minutes, the frontend updated to show the correct "User Not Found" in place of the deleted user.

Here's a video with context and the results:

https://user-images.githubusercontent.com/25919630/226913621-8b9165e5-cfac-41d8-ba10-44eea01d813c.mov

@bwbaker1 @deborahUAH this is ready to go to production. Please let us know if you have any reason why you think it shouldn't go to production (maybe @xhagrg does).

**Comment by bwbaker1** [comment]
@wrynearson I'm not able to test this on staging (don't have access to cognito).  (1) Have you tested what happens if the lead author is deleted/not found?  What about a reviewer/curator?  I just want to make sure there isn't another situation that will cause the dashboard to fail.  Otherwise, I think this looks good and is clear to users.

(2) Is there any possibility of restoring a user that for whatever reason is not found?  This is important if a user has an ongoing draft with no co-authors and is suddenly "not found."  I realized this is a separate issue/ticket.

**Comment by wrynearson** [comment]
Good points @bwbaker1 thanks.

In theory, the role should not affect the display of "User Not Found". I will test this with a new account that I made tomorrow.

From Cognito's messaging, there's no way to restore a user once they are deleted. Users need to first be "disabled" and then deleted, so the chances of this being done accidentally are very low. 

If they're lost for another reason (i.e., their unique IDs in APT and Cognito don't match for some reason), we could probably do some edits to the database to match the user's APT id with a Cognito ID, but that approach could have unintended consequences.

**Comment by wrynearson** [comment]
@bwbaker1 I was able to test it today. Here were my steps:
1. Created a new user as a contributor (Will Personal)
2. New user created a new document
3. New user invited my normal account (Will DS)
4. New user started a thread
5. Will DS replied to the thread
6. I deleted the new user (Will Personal)

Results:
- The document is in tact
- _There is no reference of the old user in the contributors section_
- Will DS is the lead author
- _The comment thread and reply (from both users) are not present_

Outcome:
1. 🟢 The site doesn't crash under this scenario
2. 🟢 The contributor (any contributor?) is set as the lead author
3. 🟡 Comments are deleted/not displayed
4. 🟡 There's no indication of the old author, and no indication that there's something wrong

Please let me know if this is acceptable behavior to push to production next week. We are thinking of ways to improve user authentication, which could be implemented in a future sprint.

cc @batpad @thenav56 @sunu

**Comment by bwbaker1** [comment]
@wrynearson Thanks for testing this.  Is it safe to assume that if there aren't any contributors on the document (just the lead author), that the entire document will be lost if the lead author's account somehow disappears?  Hopefully, this is a far fetched scenario.

I think the new behavior is acceptable to push to production. 

cc @deborahUAH

**Comment by wrynearson** [comment]
@bwbaker1 I'll test this in the next few days once I get a go-ahead from our team. I do think the content will not be completely lost, but we'll have to test for that.

**Comment by xhagrg** [comment]
This seems to be similar to the issue faced in RGT. The report should not be lost, but all interactions with the report with deleted lead would yield an error. Other aspects of the reports should work without issues.

**Comment by wrynearson** [comment]
@bwbaker1, @thenav56 tested this scenario locally with the following process:
1. Created a document using [owner@apt.com](mailto:owner@apt.com)
2. Changed the owner of atbd-version to random user sub_id
3. Checked using [curator@apt.com](mailto:curator@apt.com) account
4. Checked using [owner@apt.com](mailto:owner@apt.com) account

The document is still visible from the curator dashboard, with only the dangling user showing as a contributor. (This will say "User Not Found" on staging/production):

![2023-03-27-114212](https://user-images.githubusercontent.com/25919630/227867553-ed8ccf7e-fd42-4485-9f52-769532be8c70.png)

![2023-03-27-114203](https://user-images.githubusercontent.com/25919630/227867583-f83c9076-9bc6-4bd2-bed1-7b520a54fdb4.png)

The document is not visible/accessible for non-contributors (e.g. [owner@apt.com](mailto:owner@apt.com))
