### ISSUE TITLE
Inline citations should be in AGU format for PDF exports

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#651]
Currently, we render inline citations in the PDF in the same way that we do in the `view` mode (as a superscript number, without the tooltip).

## Current Behavior:

View: 
<img width="510" alt="image" src="https://user-images.githubusercontent.com/25919630/223399300-da3d4cdc-6ee5-4314-aa6f-5a3746946da1.png">

Current document PDF:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/25919630/223399424-218183f9-1496-4e8d-93c7-623d2a0be9fa.png">

## Expected Behavior:
- Inline citations should follow ~APA~ [AGU formatting](https://www.agu.org/Publish-with-AGU/Publish/Author-Resources/Grammar-Style-Guide#referenceformat). This means using the author's last name followed by the year (Lastname, year).

## Edge cases and assumptions
- ~There is no current field for `last name` in APT – only `Authors`, which don't have a strict style requirement
    - <img width="330" alt="image" src="https://user-images.githubusercontent.com/25919630/223400689-eafc5e69-9b81-4f03-9446-2c8b7063293b.png">
    - We assume that author's are provided in `Lastname, Firstname` format (☝️ Lastname="Hanson", Firstname="Brooks")
    - If no comma exists between names, we just take the value before any `and` in the string.
    - _Authors are not required in the frontend to add or import bibtex files._
- If two authors are provided, we should use:
    - (Lastname 1 & Lastname 2, year)
- If more than three authors are provided (Lastname1, Firstname1 and Lastname2, Firstname2 and ...), then we use the following format:
    - (Lastname1 et al., year)
- If no author is provided, we use the following format, we use the `Title` field:
    - (Title, year)
- Is no year is provided, we use "n.d."
    - (Title, n.d.)
- If no author _and_ no date is provided, we use:
    - (Title, n.d.)
    - `Titles` are required so this should be the absolute minimum situation that we encounter.~

## Acceptance Criteria
- [ ] Inline citations should be (Lastname, year) – (Smith, 2023).
- [ ] Edge cases and assumptions are used in case some combination of last name and year are not provided)

**Comment by wrynearson** [comment]
cc @batpad

**Comment by wrynearson** [comment]
@sunu please work your way through the list of edge cases more or less in order, because they are (I think)  in decreasing order of likelihood. If you can't account for all of them, it's OK – it's better to address some of them than none at all.

**Comment by wrynearson** [comment]
@frozenhelium there's some reference code already in our codebase: https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/develop/app/assets/scripts/utils/references.js#L61

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson Testing [results](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit#gid=1371486832) (row 36). 

The only issue is "et al." should always be italicized (very minor detail).  This is ready for PROD.

cc @deborahUAH @ashleyriddle92 @cw0045

**Comment by wrynearson** [comment]
@bwbaker1 I think row 36 is for something else? Did you mean row 38? 

In the [style guide](https://www.agu.org/Publish-with-AGU/Publish/Author-Resources/Grammar-Style-Guide#referenceformat:~:text=For%20references%20by%20three%20or%20more%20authors%2C%20use%20%E2%80%9Cet%20al.%E2%80%9D%20after%20the%20first%20author%3A%20(Zhang%20et%20al.%2C%202005).), here it doesn't _italicize_ et al. Could you confirm that _et al._ is in fact the AGU standard?

<img width="623" alt="image" src="https://user-images.githubusercontent.com/25919630/226646446-11edc904-9dc3-4a37-bb55-f79e844c9bef.png">

**Comment by bwbaker1** [comment]
@wrynearson I meant row 38.  I just double checked and I was wrong about italicizing et al. I think we can call this ticket done.
