### ISSUE TITLE
Reference section should follow AGU formatting guidelines

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#652]
The reference section should be in a standard format – APA was suggested by the APT team.

## Current Behavior

1. References are listed in the order that they are cited in a document

## Expected behavior

The reference section follows the [AGU style guide for references](https://www.agu.org/Publish-with-AGU/Publish/Author-Resources/Grammar-Style-Guide#referenceformat).

1. References follow the following format:
    1. Lastname, firstinitial. (year). _Title_. _Volume(issue)_, pages. Publisher. DOI
    2. Smith, B, (2019). _Title of something._ _5(6)_, 23-35. APT Publishing Corp. https://doi.org/xx.xxxx/xxxxxxxx 
        1. _(☝ without hyperlink stylizing)_
2. References are listed in alphabetical order (by the first letter of the author's last name)
    1. If only 1 author and they have the same name, list them in order of year (oldest first)
        1. Smith, B. (20`1`9)...
        2. Smith, B. (20`2`0)       
    3. If two or more authors and the same first author, order alphabetically by the 2nd author
        1. Smith, Bob & `R`accoon, Roger (2023)
        3. Smith, Bob & `Z`iller, Zilly (2018)
    4. If three...
3. If author doesn't exist, list by year provided in chronological order (after authors)
    1. Zhang, Liu (2019) ...
    2. (2019) ...
4. If author and date don't exist, list by title after author and date section.
    1. Zhang, Liu (2019). _Title_...
    2. (2019). _Title_...
    4. _Title_...

## Acceptance Criteria
- [x] Reference section includes all relevant fields in the correct format (☝️ 1.1 and 1.2)
- [x] Reference section is in alphabetical order
- [x] Reference section should only include references that are cited in the document.
- [x] Reference titles should be _italicized_
- [x] Reference volumes should be _italicized_

## Future steps
- [x] #664

**Comment by wrynearson** [comment]
@bwbaker1 and @deborahUAH, there are _many_ exceptions to the rules listed both in APA styling format requirements and in the AGU submission requirements. Sometimes AGU and APA differ, and we do not know which format and exemption to follow. Further, there are many rules related to the type of reference (journal article, book, website), but we are not tracking this information in the "add reference" section.

We strongly believe that users should be responsible for the content of their references, and not that we should rely on code to sort out their incomplete reference submissions where possible. We also think that, given the demand to deliver functioning PDF exports quickly, we do not focus our time on coding in all of the complex logic that AGU & APA demand at the current moment. Many of them seem like edge cases at this point, and serve the user very limited value (in my non-academic opinion).

In the [testing spreadsheet](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit#gid=1371486832&range=A31), I would postpone rows 31, 34, and 35.

cc @batpad

**Comment by wrynearson** [comment]
@bwbaker1 answering your question in the [testing spreadsheet](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit?disco=AAAAsjj17VY) here – we are _not_ tracking the reference type (book, journal, etc.). It's my understanding that this was agreed to before I joined the project for the purpose of feature prioritization and prioritizing ease of use.

If we think that building out a full reference manager is a valuable feature to implement, we can explore that after implementing these acceptance criteria. It would be a considerable about of work (several sprints), involving frontend, backend, and rendering changes.

cc @deborahUAH @batpad

**Comment by bwbaker1** [comment]
@wrynearson @batpad Testing results [here](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit#gid=1371486832) (rows 35-45).

The reference section is getting close (just minor formatting issues). I think this can be pushed to PROD.

cc @deborahUAH @ashleyriddle92 @cw0045

**Comment by wrynearson** [comment]
Thanks @bwbaker1 

We're looking into reference style template and seeing if we can incorporate them into our workflow. If so, it will catch many of the edge cases that you tested for. That will be worked on in future sprints.

**Comment by wrynearson** [comment]
@bwbaker1 [here](https://docs.google.com/spreadsheets/d/1EzsPAZ0dJNjreuEeCh3QlA3DIoFytadUxaydoH8xSds/edit?disco=AAAAtdXK8Qs) you're suggesting that we change the default style for references, to be applied to all references (because we currently don't track the type of reference).

**Bold** denotes a change

Current default style:

> astname1, firstinitial1, lastname2, firstinitial2, & lastname3, firstinitial3. (year). _Title_. _Volume(issue)_, pp-pp. **Publisher**. https://doi.org/xx.xxxx/xxxxxxxx

Newly suggested default style (to match a journal article (i.e., periodical) citations):

> lastname1, firstinitial1, lastname2, firstinitial2, & lastname3, firstinitial3. (year). **Title**. **_Series_**, _Volume(issue)_, pp-pp. https://doi.org/xx.xxxx/xxxxxxxx

Is this correct?

**Comment by bwbaker1** [comment]
@wrynearson Yes except "Issue" is not italicized and add a period after each author's initial.

Suggest this:
lastname1, firstinitial1., lastname2, firstinitial2., & lastname3, firstinitial3. (year). Title. _Series, Volume_(issue), pp-pp. https://doi.org/xx.xxxx/xxxxxxxx

**Comment by wrynearson** [comment]
OK thanks @bwbaker1. I can't guarantee that we'll get this lined up and tested before next Wednesday because it's a mid-sprint change, but I'll let you know if we do so that your side can test. cc @batpad @kamicut @frozenhelium

**Comment by bwbaker1** [comment]
@wrynearson No problem. This is a minor formatting detail compared to getting every merged to production.

**Comment by wrynearson** [comment]
I'm closing this ticket for now. We'll need to discuss reference section capabilities based on priorities for FY23Q3 and the scale of related features (e.g., storing the reference type)
