### ISSUE TITLE
Block equations should be numbered

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#653]
## Current behavior

Block equations are not numbered.

## Expected behavior

Block equations are numbered in order of appearance in the document.
- One number per equation
- Number should be visible only in the PDF output (not in the `view` mode)

## Acceptance Criteria

- [ ] Block equation numbers are displayed in the Document PDF (and Journal PDF later)

**Comment by frozenhelium** [comment]
@wrynearson What should be the display format?
Would something like this work? 
Equation 1:
*equation*

**Comment by wrynearson** [comment]
Sorry @frozenhelium, I thought I had an image of this 😆 

We should use a parentheses with only the number (without the .................):

Some paragraph text

$\{e} = mc^2$ .................(1)

Another paragraph

$\{e} = mc^2$ .................(2)


Here's an example from their [template](https://docs.google.com/document/d/1T4q56qZrRN5L6MGXA1UJLMgDgS-Fde9Fo4R4bwVQDF8/edit#):
<img width="687" alt="image" src="https://user-images.githubusercontent.com/25919630/226557146-de240f51-a552-4bd4-a6c3-bbfb2a789c03.png">

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this will be on staging in ~15 minutes and is ready for your review.

**Comment by bwbaker1** [comment]
@wrynearson This looks good.  I think we can call this ticket done.

cc @deborahUAH
