### ISSUE TITLE
Figures are not numbered

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#654]
## Current behavior
Figures are not numbered.

## Expected behavior
Figures (image captions, ~table captions~, other captions) are numbered in order of appearance in the document.
- Figure 1: `caption`
- Number should be visible only in the PDF output (not in the view mode)

## Acceptance Criteria
- [ ] Figure numbers are displayed in the Document PDF (and Journal PDF later)

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this will be on staging in ~15 minutes and is ready for your review.

**Comment by bwbaker1** [comment]
@wrynearson This is ready for production. We may have to tweak the formatting a bit, but that should be minor.  For example, we may need to change "Figure X:" to "Figure X." or "Figure X"

cc @deborahUAH

**Comment by wrynearson** [comment]
OK thanks @bwbaker1 – let us know what the new formatting should be and we can implement it
