### ISSUE TITLE
APT Vision and Prioritization

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#655]
Hi @deborahUAH, you had asked me to assess the direction that APT is currently going and potentially offer alternatives. First, I would like to make sure that we agree on the problems that APT is trying to solve. This will help us determine if APT is addressing those problems.

## Problems related to ATBDs:
1. ATBDs do not have a standard format or structure (file format, sections, content, etc.). This makes it difficult to compare ATBDs and to ensure that an ATBD is complete.
2. ATBDs are not centralized (there is not a repository for ATBDs). It is can be difficult to find ATBDs.
3. It’s difficult to make sure the ATBD you’re reading is the most up to date if it’s a PDF from a decentralized location.
4. There is also no governing process for revising ATBDs or requesting such a revision, nor for reviewing and approving ATBDs.

## APT vision:
APT seeks to formalize, centralize, and facilitate the ATBD creation, review, and sharing process.

I went back and checked the original 2019 SoW, back when this project was called ADaPT. These (formalize, centralize and facilitate in ATBD creation) were the main three listed goals of the project.

I would think that APT has met the first (formalize) and the third goals (facilitate in creation, review and sharing) of the original project proposal, and that our work towards the second (centralization) is sufficient for new APTDs.

The two main groups of work that DevSeed has been working on for the past ~6 months have been related to PDF generation and towards document search functionality, the former of which has been very much the top priority.

## Questions and Retrospective
1. I would like to better understand how Document PDF export fits into this vision.
    1. It seems like the Document PDF export is to have a copy of the ATBD in a decentralized place – does this go against the goal of having ATBDs centralized?
    2. If users really want to have PDFs exported for personal use (i.e., to keep next to their data), did we ever investigate better integrating APT with their data analysis tools?
    3. If users really want to have PDFs exported, does this mean that they prefer to edit the content of their ATBDs elsewhere (e.g., in a Word Doc and then copy into APT)? Does editing ATBDs in APT feel restrictive for users?
2. APT document search
    1. Have you heard from users that they would value search capabilities within APT, or would users prefer to search for ATBDs using another method (e.g., Google)?
3. Has there been user research or surveys that I could see (that probably occurred before I joined the project)? 

cc: @batpad @bwbaker1

**Comment by bwbaker1** [comment]
Closing for now.  Can discuss during planning.
