### ISSUE TITLE
Update default reference style

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#664]
_Context: https://github.com/NASA-IMPACT/nasa-apt/issues/652#issuecomment-1479627313_

The default reference style should be updated to the following:

> lastname1, firstinitial1., lastname2, firstinitial2., & lastname3, firstinitial3. (year). Title. _Series, Volume_(issue), pp-pp. https://doi.org/xx.xxxx/xxxxxxxx

This is because the most common reference type will probably be journal articles.

Currently, we don't assess reference type in the BibTeX import or reference creation.

**Comment by bwbaker1** [comment]
Note for future: We've talked about formatting everything based on AGU, which would require lots of rule writing. However, it would be great if there is an existing APA package that is simple to implement. I'm not concerned about adhering perfectly to AGU reference formatting at this point.

**Comment by bwbaker1** [comment]
@wrynearson Looks good on staging.
