### ISSUE TITLE
PRODUCTION DEPLOYMENT LIST

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#665]
We plan to push many of our recent changes to production on Wednesday, March 29th. The following will be pushed:

### Backend

- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/663
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/662
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/661
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/658
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/657
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/645
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/644
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/641
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/638
- [ ] https://github.com/NASA-IMPACT/nasa-apt/pull/637
- [ ] **CHECK IF THERE ARE MORE PRs TO MERGE**

### Frontend

- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/440
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/439
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/438
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/437
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/436
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/434
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/433
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/432
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/429
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/426
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/424
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/420
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/419
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/418
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/416
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/415
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/413
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/412
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/410
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/409
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/408
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/407
- [ ] **CHECK IF THERE ARE MORE PRs TO MERGE**

### What we're still working on
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/417

## Production Deploy Checklist

- [ ] @sunu and @batpad to review this checklist
- [ ] @naomatheus to make sure all required PRs are deployed to production
- [ ] @frozenhelium to ensure @naomatheus knows what's needed regarding AWS Cognito settings for #608

**Comment by naomatheus** [comment]
Backend - Checklist

- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/663
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/662
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/661
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/658
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/657
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/645
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/644
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/641
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/638
- [x]  https://github.com/NASA-IMPACT/nasa-apt/pull/637

**Comment by naomatheus** [comment]
Frontend - Checklist

- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/440
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/439
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/438
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/437
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/436
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/434
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/433
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/432
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/429
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/426
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/424
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/420
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/419
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/418
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/416
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/415
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/413
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/412
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/410
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/409
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/408
- [ ]  https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/407
