### ISSUE TITLE
Timeboxed comparative analysis of automated testing options

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#668]
While most of our portfolio uses Cypress, it would be good to make sure that that's the best approach for APT.

@kamicut if you could do some surface-level comparison between Cypress, Playwright, or any other automated testing solution you find/recommend?

Let's try to have this done early next week (by Tuesday, April 4th in the morning), so we can discuss next steps later that day.

cc @batpad

**Comment by kamicut** [comment]
@wrynearson I've installed playwright and have read some of the docs. I think I need a little bit more time to test out one of the trickier things in these test runners which is authentication. I'll be working on this today (Tuesday 4th). All in all, I think it can do everything Cypress can do, but with some added bonuses such as integration into VS Code for debugging and faster startup and execution time for tests.

**Comment by wrynearson** [comment]
Great, thanks @kamicut! Seems like Playwright is the way to go unless we get any compelling reasons not to use it? 

cc @sunu @frozenhelium @thenav56 @batpad

**Comment by wrynearson** [comment]
@kamicut let us know when we're finalized with Playwright, and then we can have a ticket or two for implementing the tests.

cc @sunu @batpad
