### ISSUE TITLE
Move Public OpenSearch Domain to VPC (public to private)

### ISSUE THREAD

**Issue by naomatheus** [NASA-IMPACT/nasa-apt#700]
### Summary

The MCP Cloud Management Team (Shawn, Caden, Chris) has identified the need to move our current public OpenSearch domain into an existing VPC, creating a private OpenSearch domain and endpoint. This will enhance the security and privacy of our data. Though we are behind on the remediation date, it is recommended to make this change as soon as possible.

### Steps to Move OpenSearch Domain into VPC and Retain Indexed Data

- Create a snapshot of the existing public OpenSearch domain data.
  - [Creating manual snapshots](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-snapshots.html)
- Configure security groups within the existing VPC to control access to the new private OpenSearch domain.
  - [Creating security groups](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html)
- Create a new private OpenSearch domain within the VPC.
  - [Creating VPC-based domains](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/vpc.html)
    - When creating a VPC-based domain, you need to specify the VPC ID, and one or more subnet IDs. You also need to configure security groups to control traffic to your domain.
- Restore the snapshot taken in step 1 to the new private OpenSearch domain.
  - [Restoring snapshots](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-snapshots.html#managedomains-snapshot-restore)
- Update any applications or services to use the new private OpenSearch endpoint.
  - This is APT Lambda, SQS Lambda, and Frontend application
- Verify data consistency and connectivity to the new private OpenSearch domain.
- Once the new private OpenSearch domain is operational, decommission the old public OpenSearch domain.
  - [Deleting OpenSearch domains](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/gsgdeleting.html)

**Comment by naomatheus** [comment]
Here is the full ticket from MCP internal system:

Details13/Mar/23 1:22 PM
Priority
Medium
Description
MCP is performing Yearly reviews of Security Hub and ATO Continuous Monitoring things and require your support in remediating a finding in one or more of your accounts.
Elasticsearch domains should be in a VPC
[ES.2] This control checks whether Elasticsearch domains are in a VPC. It does not evaluate the VPC subnet routing configuration to determine public reachability. This AWS control also does not check whether the Amazon OpenSearch Service resource-based policy permits public access by other accounts or external entities. You should ensure that Elasticsearch domains are not attached to public subnets. See Resource-based policies (https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html#es-ac-types-resource) in the Amazon OpenSearch Service (successor to Amazon Elasticsearch Service) Developer Guide. You should also ensure that your VPC is configured according to the recommended best practices. See Security best practices for your VPC (https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-best-practices.html) in the Amazon VPC User Guide. [Remediation instructions](https://docs.aws.amazon.com/console/securityhub/ES.2/remediation)
OpenSearch domains should be in a VPC
[Opensearch.2] This control checks Amazon OpenSearch Service domains are in an Amazon Virtual Private Cloud (VPC). [Remediation instructions](https://docs.aws.amazon.com/console/securityhub/Opensearch.2/remediation)
ServiceCompliance StatusSeverityWorkflowAccountResourceRegionUpdatedESFAILEDCRITICALNEW237694371684arn:aws:es:us-west-2:237694371684:domain/apt-api-lambda-prod-elasticus-west-22023-03-13T17:01:07.201ZOSFAILEDCRITICALNEW237694371684arn:aws:es:us-west-2:237694371684:domain/pi-lambda-prod-v2-opensearchus-west-22023-03-13T06:34:01.470Z
Critical Findings have a 15 day turn-around if at all possible.
The current tentative remediation date is 4/3/2023. Remediation instructions are linked above. LMK if you have any questions.
Remediation Type
Security Hub
Due Date
02/Apr/23
Account Number
237694371684
AWS Region
us-west-2 (Oregon)


![image](https://user-images.githubusercontent.com/25667086/232873906-fc1a36af-98fa-444d-9f69-fb436cd50912.png)

**Comment by sunu** [comment]
@naomatheus If I'm not mistaken, step 2, 3 and 5 could be done through our cdk config in https://github.com/NASA-IMPACT/nasa-apt/blob/bbca71b50a8937b8d6713c307c0159a05b266161/stack/app.py#L173 by adding the right security group and vpc config to the domain creation function, right?

**Comment by naomatheus** [comment]
Yes I would agree @sunu . We can complete a lot of this with small changes to the infrastructure code. And actually we should implement all of this in CDK.

**Comment by naomatheus** [comment]
I removed myself from this issue for now since @sunu  will be first on this task.
I'm happy to support where necessary and for deployment to production.

cc: @wrynearson

**Comment by wrynearson** [comment]
@sunu any updates here? Is any more work needed?

**Comment by sunu** [comment]
@wrynearson Sorry, I somehow missed this. Looking at the linked PR (https://github.com/NASA-IMPACT/nasa-apt/pull/703), it needs some more tweaks. After that we can test on staging and then production.

**Comment by wrynearson** [comment]
No problem, thanks @sunu

**Comment by bwbaker1** [comment]
@wrynearson Should we move this into a sprint since MCP is requesting this get completed?

**Comment by wrynearson** [comment]
@bwbaker1 this is complete. I forgot to close the ticket.
