### ISSUE TITLE
Update AWS Architecture Diagram

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#710]
We should update our AWS Architecture Diagram. IMPACT is hoping to have it as soon as possible (this sprint if possible, or next sprint).

- [x] Find existing AWS Architecture diagram
- [x] Update AWS Architecture Diagram

cc @sunu @batpad

**Comment by naomatheus** [comment]
#712  is up for review to address this
cc @wrynearson

**Comment by wrynearson** [comment]
Thanks @naomatheus , let's wait for @sunu to review

**Comment by bwbaker1** [comment]
I think the diagram needs to be added [here](https://docs.google.com/presentation/d/1YFRjXt5iaFrx0_ZkUmB5-oB77_Lj4yAMVy54U4o85R0/edit#slide=id.g21ec47531b7_0_89) once it is ready.

**Comment by wrynearson** [comment]
@naomatheus to work on this during sprint 3

**Comment by wrynearson** [comment]
Hey @naomatheus, are you able to work on this during this week?

**Comment by wrynearson** [comment]
FYI @bwbaker1 the AWS architecture diagram has been updated, and is linked in the `README` of this repo
