### ISSUE TITLE
Submit STI for Jamboree poster

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#724]
### **Description:**
We must submit a STI for the jamboree poster. The deadline is June 11 but earlier is better. 

### **Tasks:**
- [ ] Submit STI

### **Acceptance Criteria:**
- [ ] STI is approved

**Comment by ashleyriddle92** [comment]
Where are the guidelines for the STI?

**Comment by bwbaker1** [comment]
@ashleyriddle92  It's just a [form](https://drive.google.com/drive/search?q=sti).
