### ISSUE TITLE
Backend API + Database changes to allow ATBDs to have either uploaded PDF or document content

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#725]

**Comment by sunu** [comment]
The basic idea is to keep using the same ATBD table for ATBDs that represent uploaded PDFs as well. We plan to add an optional `pdf` field to the ATBDs that will reference the uploaded PDF file. The `document` field of the ATBDs representing uploaded PDFs will be set to null. We can also add a type field to store a value to represent whether the ATBD was written on APT or uploaded as a PDF.

**Comment by thenav56** [comment]
Maybe we use AtbdVersions instead to store the pdf? That way we can also use versions.
Most of the flow in APT uses AtbdVersions instead of Atbd directly.

**Comment by sunu** [comment]
@thenav56 yes, definitely. Sorry for the confusion. I meant the `AtbdVersions` model as well.

**Comment by wrynearson** [comment]
@sunu @thenav56 closing this as I think it's done. Let me know if I'm wrong.
