### ISSUE TITLE
Handle PDF uploads

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#727]
- [x] Backend: https://github.com/NASA-IMPACT/nasa-apt/pull/742
- [x] Frontend: https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/486

**Comment by sunu** [comment]
AWS API gateway has a [default payload size limit](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#http-api-quotas) of 10 MB. To work around that limit while uploading PDFs, we will implement a endpoint that lets the frontend upload PDFs directly to S3 through a signed url.

**Comment by wrynearson** [comment]
Sorry @sunu and @thenav56, is this ticket fixed with https://github.com/NASA-IMPACT/nasa-apt/pull/742, or is this separate?

**Comment by sunu** [comment]
@wrynearson #742 implemented the backend part, https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/486 should handle the frontend portion.
