### ISSUE TITLE
Update AMI for deployment EC2 instance

### ISSUE THREAD

**Issue by naomatheus** [NASA-IMPACT/nasa-apt#729]
## Summary

Internal infrastructure team recently updated their allowed AMIs for AWS EC2 instances. One of our deployment bastion hosts was flagged as using an outdated AMI (amazon machine image). In coordination with internal infrastructure team this instance has been redeployed with an AMI included in the list of "Golden AMIs" that are allowed for use.

Redeployment was completed on 5/3/2023 according to internal logs. 

cc @wrynearson

**Comment by naomatheus** [comment]
Closing as this task was completed.

**Comment by wrynearson** [comment]
Thanks @naomatheus !
