### ISSUE TITLE
Add link to PDF upload modal in new document info modal

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#733]
<img width="1648" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/5b8c8e75-b15e-4eeb-bdf5-897112e8eec4">

**Comment by wrynearson** [comment]
@frozenhelium made a good point that we need introductory ATBD information before users upload PDFs. Because of this, I'd suggest to _not_ add a link to the PDF Upload process here and instead have users use https://github.com/NASA-IMPACT/nasa-apt/issues/734 to upload PDFs.

**Comment by bwbaker1** [comment]
@wrynearson ^ Agreed. Let's not have the PDF upload link on new document modal.
