### ISSUE TITLE
UI Text Prompts: A few edits from testing

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#741]
### **Description**
APT UI text prompts were recently updated, but a few edits are needed. 

### **Acceptance Criteria:**
-  [ ] [These edits](https://docs.google.com/presentation/d/1ATn2WE8tzyQunRZdNSD7ytPGAIMakccTPI4BvKeXOIs/edit#slide=id.g2459c3ae95e_0_3) are made

**Comment by bwbaker1** [comment]
@wrynearson I found a few more needed edits to the UI text. This should only take a few minutes.

**Comment by wrynearson** [comment]
OK thanks @bwbaker1, I'll get those updated this week
