### ISSUE TITLE
Hide/Remove Journal PDF download option

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#744]
Currently, users have two format options for downloading PDFs of their ATBDs:
1. Document PDF
2. Journal PDF

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/3fe57e21-193c-4f6e-8ac8-a686fa908084)

The Journal PDFs are not in a well-functioning state (which currently use $LaTeX$ instead of our new HTML-based approach). We should remove this download option until we update it to our HTML-based approach.

## Acceptance Criteria

- [ ] The `Journal PDF` download option should be removed so users cannot download `Journal PDFs`

**Comment by wrynearson** [comment]
@bwbaker1 this is on staging and is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This is much cleaner!  It can be added to the next production deployment.
