### ISSUE TITLE
Make user guides publicly downloadable

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#750]
### **Description**
Some of our users may be interested in downloading a PDF version of the user guides. Therefore, it would be nice to make those available, specifically when the guides are done.

### **Tasks:**
- [ ] Determine the best way to make these available - export google doc version of document and make them downloadable

### **Acceptance Criteria**
- [ ] Users guides are downloadable

**Comment by wrynearson** [comment]
@bwbaker1 I think this would be a good issue to think about what pain point we're trying to solve first. You mentioned that users had hoped to have the user guide open in one window while creating their ATBD in another?

If that's the problem, I think the best and simplest solution would be to have them have APT open in two windows – one on the user guide, and one on their ATBD. That way, if the user guide gets updated, they're always viewing live information.

If users are constantly having to refer to content in the user guide, another good approach could be to give the guidance users need where they need it (e.g., where we're linking help videos to the location in question).

If users want to keep this content in a static and offline location, then downloading the user guide could be a good option. @sunu, @kamicut or @batpad – do you know of a way we can serve markdown files we have as a PDF? If the internal Google Doc is the "source of truth", we could export that as a PDF, host it somewhere, and link to it in a download button.

**Comment by bwbaker1** [comment]
@wrynearson The feedback is related to some of our users still taking an old school approach and prefer downloading documents locally. I think we can take a simple approach, similar to how we treat the ATBD template downloads. 

This is by no means a big priority though. It may be best to just keep this issue in the backlog and close as not planned.

**Comment by wrynearson** [comment]
OK, good to know the motivation/feedback, thanks. I put it in the backlog sprint for now.

**Comment by bwbaker1** [comment]
Closing as not planned for now.
