### ISSUE TITLE
PDF Upload link error when users has no existing documents

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#754]
###**Description**
When a user doesn't have any existing documents, the "Create document" button under the "Documents" tab of the dashboard still has the old link to create an ATBD within APT. 

![Image](https://user-images.githubusercontent.com/56319064/244793015-3a7965ea-c230-4180-9882-4d8fbf6f002e.png)

Next page is this

![Image](https://user-images.githubusercontent.com/56319064/244793106-f9d6f6c7-ab7a-4968-8bcb-dd986bbc9570.png)

And then the APT editor

![Image](https://user-images.githubusercontent.com/56319064/244793130-54789b76-c7b3-4f8d-8bee-ad3f9bc466be.png)

**Comment by bwbaker1** [comment]
@wrynearson  I think this a simple link issue.

**Comment by wrynearson** [comment]
Thanks for flagging this, we'll get that fixed soon. cc @sunu

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for review on staging

**Comment by bwbaker1** [comment]
@wrynearson We tested this and it is working properly now. Thanks for the quick fix!
