### ISSUE TITLE
Update "welcome to your new document" text to reflect pdf upload workflow

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#756]
### **Description**
When a user creates a new document in APT, they are prompted with a "welcome to your new document" popup. This needs to be updated to reflect the new user workflow.

### **Tasks:**
- [x] Update the content of this page [here](https://docs.google.com/document/d/1CLhceTZvaxYMBKFohtVMhZMZUb3t90lpx7oeTH9MTn4/edit)

### **Acceptance Criteria**
- [x] Send updated version to DevSeed for implementation

**Comment by bwbaker1** [comment]
@wrynearson How difficult would it be to have two slightly different versions of this prompt, 1) create a new ATBD in APT workflow and 2) PDF upload workflow?

**Comment by wrynearson** [comment]
@frozenhelium @kamicut thoughts on having two different versions of the welcome modal?

<img width="839" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/4477b669-49d3-4448-a412-4e94195ac92d">

I'm guessing that the PDF upload welcome modal would have fewer steps, but we'll need to work out the specific details and text.

**Comment by wrynearson** [comment]
@bwbaker1 this will be fairly straightforward. Once you send us the desired text, we can create a new popup modal.

**Comment by bwbaker1** [comment]
@wrynearson [Here](https://docs.google.com/document/d/1CLhceTZvaxYMBKFohtVMhZMZUb3t90lpx7oeTH9MTn4/edit) is updated text for the PDF upload workflow.

**Comment by wrynearson** [comment]
Thanks @bwbaker1, cc @kamicut or @frozenhelium (whoever would rather take this on)

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review.

**Comment by bwbaker1** [comment]
@wrynearson Looks good. Moving to ready for prod.
