### ISSUE TITLE
Document repository page and the search results show different sets of documents

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt#759]
The document repository page at `/documents` shows all documents accessible to the current user. But once we search for a particular query on the documents repository page, the results only include results from public documents. This inconsistency can be confusing for users.

We should let users search through all documents they have access to or show only public documents on the document repository page to be consistent.

**Comment by bwbaker1** [comment]
@wrynearson @sunu This was recently brought to my attention while meeting with a user. I didn't realize that a user can see every single document that is published or a draft (including drafts they are not collaborators on). I think it is best to only show public documents from the "Explore existing documents" tab (see image below). They can see their own documents from the dashboard. Nonetheless, they do not need access to others drafts.



![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/41ad9803-8ce6-44ea-a7ed-8abe1c7f7a6d)

**Comment by kamicut** [comment]
This issue involves two changes:

- `/documents/` should only show public documents
- The dashboard should only show the user's documents, published documents, **and drafts they are a collaborator on**

@bwbaker1 can you confirm?

**Comment by wrynearson** [comment]
@bwbaker1 for the 2nd issue, we have two dashboards. One for document contributors/reviewers (1), and one for administrators (2).

1. <img width="1297" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/d3ad70f8-9df0-433b-a1a3-dbff47ca8e04">
2. <img width="1363" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/00111d30-1278-40bc-8912-39da4e9b6f81">

For the admin dashboard (2), we should be able to see _all_ documents, regardless of their status. Can you confirm that the user is seeing _all_ reports in their dashboard but should only have access to the contributor/reviewer (1) dashboard?

**Comment by bwbaker1** [comment]
@wrynearson @kamicut There shouldn't be any changes to either the user or admin dashboard. These show the documents correctly. The only needed change is /documents/ should only show published documents. This is true whether a user is logged in or not.

**Comment by sunu** [comment]
I've created a PR in the frontend repo with a fix: https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/587

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This looks good! It's ready for production.
