### ISSUE TITLE
Plain language summary disappears when atbd moved to review (on production)

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#762]
### **Description**
When an ATBD (uploaded PDF) is moved from draft to review, the plain language summary disappears. 
Also occurs with documents created in APT interface as well. So both user workflows has issue. 

Draft status

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/8edf6da2-5915-489c-8a86-2b3b9a159de0)

Review status

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/c3179efc-d0eb-4e7e-a55f-c559d697424e)

### **Acceptance Criteria**
- [ ] determine/resolve what is causing the plain language summary to disappear

cc @wrynearson

**Comment by wrynearson** [comment]
Hey @bwbaker1, thanks for flagging this. We won't be able to get to it, but we'll look at it first thing next week (cc @thenav56 @sunu)

**Comment by sunu** [comment]
@wrynearson this should already be fixed in prod by https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/523

**Comment by wrynearson** [comment]
Thanks for flagging this @sunu !
