### ISSUE TITLE
PDF downloads sometimes do not show in the local directory

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#770]
### **Description**
User notified me that when downloading a PDF, he does not see it in the "downloads" directory and he cannot find it. We did some internal testing and found this.

1. PDFs download as expected to the "downloads" directory on MacBook (checked Chrome and Safari).
2. PDFs _**do not**_ seem to download to a directory on PC (checked with Chrome). Tester did receive a toast stating that the PDF was successfully downloaded. See video.

https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/50be3006-ee10-46a5-92fe-c8f4993de478

### **Acceptance Criteria:**
- [ ] PDF downloads to the appropriate directory for all users

**Comment by bwbaker1** [comment]
@frozenhelium @sunu @thenav56  Could one of you look into this issue?

**Comment by thenav56** [comment]
@bwbaker1 @frozenhelium @sunu
With a quick glance, it looks like the browser has blocked the download popup. You can see it in the top right corner of the address bar at 0:30.

![2023-07-12-085020](https://github.com/NASA-IMPACT/nasa-apt/assets/7059255/415fc003-9b73-4c30-a8da-6c010618c6e8)

Maybe we can add a message in the notification saying the user needs to enable the popup or provide the link to download/view.

**Comment by sunu** [comment]
Yea, looks like Chrome is blocking the download popup.

@bwbaker1 Could you try out these instructions to allow popups on APT site and see if that fixes the issue for the user: https://support.google.com/chrome/answer/95472?hl=en&co=GENIE.Platform=Desktop. The instructions are under the "Allow pop-ups and redirects from a site" section.

**Comment by bwbaker1** [comment]
@sunu @thenav56 That solved the issue. I think it will be more user friendly if we provide the link to download/view. Thoughts?

**Comment by sunu** [comment]
@bwbaker1 Yes, we can include the link directly in the notification as well.

**Comment by bwbaker1** [comment]
@wrynearson Looks good on staging.

**Comment by wrynearson** [comment]
Right now, we instruct users to allow pop-ups. It would be better if we added a download link directly in the success toast. I'll close this ticket for now, but we could add that feature in a new ticket later.
