### ISSUE TITLE
FY23.4 Objective 1: Implement AGU Journal Styling and PDF Generation

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#778]
## **Objective Statement**
Implement the ability to generate journal ready PDFs that users to submit their ATBDs directly to AGU's Earth and Space Science journal.

## **Motivation**
APT's partnership with AGU's Earth and Space Science journal allows users to download their ATBD as a journal manuscript for easier submission. Currently, APT does not have the capability to generate journal ready PDFs.

## **Description**
Make changes needed to implement journal PDFs, which includes styling requirements, adding line numbers, and ensuring all necessary journal detail sections are included.

## **Acceptance Criteria**
- [x] Users can download their ATBD for AGU ESS journal submission (Journal PDFs)
- [ ] Journal PDFs are correctly styled
- [x] General PDFs contain the "Discussion" section

```[tasklist]
### Objective Issues
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/649
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/421
- [ ] https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/425
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/682
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/786
```

**Comment by wrynearson** [comment]
@bwbaker1 thanks for making this ticket! I've updated the "Objective Issues" to use Github's tasklist feature. That allows us to track progress of the PI Objective based on the status of the Objective Issues
