### ISSUE TITLE
Reference edit button is not working

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#780]
### **Description**
A current user discovered that the reference edit button is no longer working. It is not clickable.  However, the delete button still works. 

https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/56319064/9b1ac3ed-ce64-4881-a505-8da89b3e6324

### **Acceptance Criteria**
- [ ] Determine what is causing the edit button to not work.
- [ ] A solution is implemented

cc @wrynearson

**Comment by bwbaker1** [comment]
@frozenhelium @kamicut @batpad Has anyone had a chance to look at this bug?

**Comment by batpad** [comment]
We are taking a look today and will have an update by end of day.

**Comment by bwbaker1** [comment]
@batpad Cool, thank you!

**Comment by kamicut** [comment]
I've addressed the issue in this PR: https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/531

**Comment by bwbaker1** [comment]
@wrynearson Now working on staging.
