### ISSUE TITLE
References on generated PDFs have different font size

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#781]
### **Description**
1. References on PDFs have a different font size than the document text. It is smaller. See image below.

2. When multiple references are cited at the same time, there should only be one parenthesis  around all of the references.  See the first example image below. The first red box is (Armston et al., 2013) ; (NI-Meister et al., 2010). It should look like this:
(Armston et al., 2013; Ni-Meister et al., 2010). 

3. There should not be a parenthesis when a sentence begins a reference. See example image two. 

Example image one.
![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/72151651-ee31-4811-99f0-f255f27e6838)

Example image two.
![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/eee89e8a-0353-415c-89f0-7ebfacd8a40f)

```[tasklist]
### Acceptance Criteria
- [ ] References in the PDF have the same font size as the paragraph text
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/784
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/785
```

**Comment by bwbaker1** [comment]
@wrynearson I would like for this to be scoped out and see potential LOE. We are going to get the same feedback from all users regarding these issues.  I understand this may be a bigger effort than we can tackle this PI.

**Comment by wrynearson** [comment]
1. The first issue was a design choice for readability in the view mode. We can change it to be the standard text size in the PDF.
2. We'll look into this
3. We'll look into this

Out of curiosity, were these known issues or did you just discover them? I ask because they've been on production for some time now.

**Comment by bwbaker1** [comment]
@wrynearson Ok, I think that will be good to change it to standard text.

We used to have a ticket for issues 2 and 3, but I guess it kept getting deprioritized for other things. I'm thinking it was about two years ago when it was noted.  This is the first time we are getting user feedback regarding it.  The feedback was from two reviewers that aren't happy with it.

**Comment by wrynearson** [comment]
@kamicut we can talk about this next week. @frozenhelium I think only Acceptance Criteria 1 is relevant for you

**Comment by bwbaker1** [comment]
@wrynearson I found these two closed tickets (#431 and #284). So it seems this issues were discarded because it wasn't possible with the old Latex model. Maybe these tickets will be useful when you guys discuss this.

**Comment by wrynearson** [comment]
OK thanks @bwbaker1, we'll look into it. How urgent are issues 2 and 3?

**Comment by bwbaker1** [comment]
@wrynearson I think just looking into it will be fine for now. I have a few meetings planned with users over the next few weeks, so I should find out what they see as being urgent improvements.

**Comment by wrynearson** [comment]
@bwbaker1 the font size is updated on staging. Let me know if that's the styling you were expecting (both for view and PDF modes).

**Comment by bwbaker1** [comment]
@wrynearson The reference font still looks quite a bit smaller than the text font.

**Comment by wrynearson** [comment]
Try force-refreshing again. This should have updated and is set to be the same size as the paragraph text.

**Comment by sunu** [comment]
@bwbaker1 if you're checking the font size in an exported PDF, it could be cached. To make sure that the PDF isn't from cache, could you consider creating a new ATBD or slightly modifying the current one?

**Comment by wrynearson** [comment]
@bwbaker1 I've split this into multiple tickets. This is tracking the font size, while the other two issues are tracked in #784 and #785

**Comment by bwbaker1** [comment]
@wrynearson Font size looks good now. Just realized there are multiple tickets for reference fixes.
