### ISSUE TITLE
Implementing line numbering for journal PDFs

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt#786]
We are going to generate line numbers for journal PDFs on the backend. To do that we will:

- [x] Calculate line positions using [pdfplumber](https://github.com/jsvine/pdfplumber)
- [x] Write the actual line number string to the calculated line number positions using the absolute co-ordinates
- [x] Return the new pdf with line numbers as the output of journal pdf export

refs #649

**Comment by wrynearson** [comment]
This is ready, but is "blocked" until we finish https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/421 so we can deploy all Journal PDF changes to staging.
