### ISSUE TITLE
Ensure Elasticsearch/OpenSearch domains have encryption at-rest enabled

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt#788]

**Comment by bwbaker1** [comment]
@wrynearson Should we move this into a sprint since MCP is requesting this be completed?

**Comment by wrynearson** [comment]
Yes good idea, I added it to sprint 3.

**Comment by leothomas** [comment]
Update: encryption-at-rest has been abled on the OpenSearch instance in MCP. PR for adding encryption at rest to the CDK template open here: https://github.com/NASA-IMPACT/nasa-apt/pull/804

**Comment by wrynearson** [comment]
cc @ChrisPhillips1024
