### ISSUE TITLE
Add encryption at-rest to the RDS database used by APT in production

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt#789]

**Comment by bwbaker1** [comment]
@wrynearson Should we move this into a sprint since MCP is requesting this be completed?

**Comment by wrynearson** [comment]
Yes, good catch. I added it to Sprint 3

**Comment by leothomas** [comment]
@sunu and I took at a look at this yesterday. Encryption-at-rest can only be enabled when creating the database, so we will need to migrate the data: 
1. Manually take a snapshot of the database
2. Rename the database in the CDK script to ensure Cloudformation removes and re-deploys the database (with encryption)
3. Restore the new database from the Snapshot saved in Step 1

**Comment by sunu** [comment]
The steps need to be slightly different since AWS doesn't allow restoring a snapshot to an existing RDS instance either:

1. We manually take a snapshot of the database and create an encrypted copy of it.
2. We restore the encrypted copy to a new database
3. We tweak the CDK scripts to ensure it uses the new database
4. After confirming everything works fine, delete the old database

**Comment by leothomas** [comment]
Oh great catch, I didn't realize the snapshot had to be encrypted first.  Here' s a [tutorial](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/encrypt-an-existing-amazon-rds-for-postgresql-db-instance.html) for reference

**Comment by wrynearson** [comment]
@bwbaker1 this will be deployed today. cc @ChrisPhillips1024

**Comment by sunu** [comment]
We have deleted the old unencrypted instance now after making sure the migration went fine.

**Comment by wrynearson** [comment]
cc @ChrisPhillips1024 ☝️
