### ISSUE TITLE
Consider using feature flags on the frontend

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt#790]
Sometimes we want to enable certain functionalities in certain environments but disable them in other environments. For example, while we use 2FA on staging and prod, we need a way to avoid that in dev mode. Similarly, we had a discussion on slack recently that we want to test journal export on staging gradually without exposing it to users on prod. Feature flags could be useful in these cases by letting us use the same code in different environments but still helping us control which features we expose to users.

One possible way to implement feature flags would be to have a `/metadata` endpoint that exposes app metadata (eg: app title etc) along with `feature_flags`. The React frontend would call this endpoint during initialization and use the values in `feature_flags` to selectively expose or hide certain feature. For example, the journal export button would be visible only if `JOURNAL_EXPORT_ENABLED` is set to `true` in `feature_flags` and so on.

**Comment by wrynearson** [comment]
@bwbaker1 not much for you to review here, but feel free to 😄. This lets us have certain functionality enabled on staging but not on production, which helps with our testing locally -> staging -> production pipeline.
