### ISSUE TITLE
APT sticker design

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#794]
### **Description**
IMPACT projects are designing stickers to hand out at conferences, etc. APT is working with Outreach and Communications to design this sticker. We are working on suggesting sticker content.

### **Acceptance Criteria:**
- [x] APT sticker design

**Comment by bwbaker1** [comment]
@cw0045 @ashleyriddle92 Thought i would add a ticket so we can track that we are working on the general design. This isn't tracking Ashley's actual time of creating the sticker.

**Comment by wrynearson** [comment]
Our designer @LanesGood put together a quick mock-up of a sticker idea, based on Ashley's first design.

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/8ca71c6b-779e-4b36-8a3b-e89d4aeb4e26)

Let us know what you think, and if you'd like us to tweak it or provide higher-resolution files
