### ISSUE TITLE
Form/download counter to collect ATBD template downloads

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#798]
### **Description**
We are currently keeping track of user metrics for those creating ATBDs within the APT environment (e.g., # of users, ATBDs, etc.). However, we currently do not have a way to track how many people are choosing the ATBD template workflow. Note: this request is from Cerese. These metrics will be included in the monthly report to HQ.

A few options have been discussed:

(1) track the number of downloads - this will be good to know but will not reflect an accurate number of users going this route. 
(2) add a form for users to complete - ask a few questions, such as name, science team, and when they expect to deliver the completed template to APT. This would be framed so that we are expressing the desire to provide user support during this process. The drawbacks are that not everyone will fill out the form and users find forms annoying, even short ones. 

### **Acceptance Criteria:**
- [x] options are scoped out (doesn't have to be limited to the noted options above)
The selected option is implemented and results are stored/shared so the curator has access
- [x] create google form: https://docs.google.com/forms/d/1EmDfmObsicWEGdDAThCfPvvsotNV7h6eFsAmtZnBUI0/edit
- [ ] make template downloads only available to approved users
- [ ] provide one example template (maybe add watermark so that it can't be used)
- [ ] add user survey form to template download

cc @wrynearson

**Comment by wrynearson** [comment]
@batpad do you want to help me think through the best way to capture this information?

**Comment by wrynearson** [comment]
@bwbaker1 we think the best way to accomplish this is setting up Google Analytics. That way, if we want to add more data points later, it will be easy.

I think other IMPACT projects use Google Analytic. Do you know if there's an IMPACT account that we could add APT to?

From there, we can scope out the custom analytics to capture.

@kamicut – could you take this on?

**Comment by bwbaker1** [comment]
@wrynearson Google Analytics sounds good, especially for long-term metrics. We may still have to provide a form upon template download because HQ wants downloader's (1) name (2) email (3) science team and (4) estimated time of delivering ATBD to APT. 

We can make this form optional, but we can provide a description that notes we are interested in this information so that we can better provide user support.

**Comment by wrynearson** [comment]
OK, thanks @bwbaker1. Do you know why HQ wants/needs this information? Is point 4 something they're envisioning asking users in the form, or something we can calculate (download -> upload time)?

Another option would be to only allow for form downloads when a user is logged in. That way, users wouldn't have to re-enter information they've already provided (so far name and email).

**Comment by bwbaker1** [comment]
@wrynearson HQ (and us) want to track how many users are using the templates. Currently, we have a good idea of what ATBDs are actively being worked on within the tool, and therefore the active users/science teams. However, we have no idea of who, if anyone, is working on a template. 

I provide this information to Cerese each month. It's will be important during our 1-year maintenance mode to track all active users because this could impact the final decision on APT next year.

Point number 4 is something we would ask on the form. I don't think the actual time between download and upload is too important (would be a good long-term metric though). The issue is we want to know individual user's expected timeline. For example, the PACE team is starting to work on ATBDs now for an instrument that will be launched next year. Since they will not have data until next spring/summer, their ATBDs likely won't be done for a while.

Your last point is good. We can look into this, but I think we discussed before making sure that the templates are publicly available.

**Comment by wrynearson** [comment]
Let's chat more on Monday about this to come up with a good solution.

**Comment by wrynearson** [comment]
Closing this in favor of https://github.com/NASA-IMPACT/nasa-apt/issues/807. If https://github.com/NASA-IMPACT/nasa-apt/issues/807 doesn't provide the required information, we can re-open this. Let me know @bwbaker1 if you have any objections.
