### ISSUE TITLE
Add new section/subsection "Retrieval Error Estimates/Uncertainties"

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#799]
### **Description**
Several users have pointed out that we are missing an important section/subsection of the ATBD related to "Retrieval Error Estimates and Uncertainties. It is anticipated that most users will need this section but not all. Therefore, we need to determine how to treat this section (i.e., optional or have some informative placeholder text - see outcome #802).

Initial thinking is that this section should follow the "Mathematical Theory/Assumptions" section and would be 
(1) Retrieval Error Estimates
(2) Retrieval Error Uncertainties

However, it doesn't necessarily fit there nor does it fit within the Algorithm Performance Assessment section. Placement needs discussion.

### **Acceptance Criteria**
- [ ] Options are scoped out 
- [ ] The decided solution is implemented and this section is added to both general and journal PDFs

cc @wrynearson

**Comment by wrynearson** [comment]
@frozenhelium could you share how complex it would be to add a new section to ATBDs (edit, view and both PDFs)

**Comment by wrynearson** [comment]
@bwbaker1 could you help us scope this out further? Or should we put this in the FY24 backlog?

**Comment by bwbaker1** [comment]
@wrynearson I think it would be best if we could get this completed FY23, if possible. Let's add a new section within the "Algorithm Description" step between "Mathematical Theory" and "Algorithm Input Variables." Let's call this section "Retrieval Assessment" and it will have the subsection "Retrieval Uncertainty Estimates." It should include the rich text editor.

Between these two.
<img width="1296" alt="Screen Shot 2023-09-27 at 11 35 08 AM" src="https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/d77c3835-cfae-4659-81f9-894e4ffcf648">


So the TOC and section headers would look like this:
3. Algorithm Description
   3.1 Scientific Theory
      3.1.1 Assumptions 
   3.2 Mathematical Theory
      3.2.1 Assumptions
   3.3 Retrieval Assessment
      3.3.1 Retrieval Uncertainty Estimates
   3.4 Algorithm Input Variables
   3.5 Algorithm Output Variables

The text prompt should be this.

3.3.1 Retrieval Uncertainty Estimates
"Describe the uncertainty and/or errors applicable for the observational retrievals. This can include uncertainty in the scientific or mathematical methods used." 

Side note. We will need to update the text prompt for Algorithm Usage -> Performance Assessment -> Uncertainties to the following: 

"Describe the uncertainties applicable to the validation methods."

Let me know if this isn't clear. I may have some edits to the text prompt after I think about it more.

**Comment by wrynearson** [comment]
@bwbaker1 I don't think we'll be able to complete this by mid next week, with all of the remaining tickets scheduled for this sprint. If we do finish the other tickets in time, we'll look at this.

**Comment by bwbaker1** [comment]
@wrynearson Understood. If you all can't get to this, we may be able to just add some additional text to the text prompt. Something like "If you have retrieval uncertainties, please add a new subsection within X section and describe...." We can talk about this next week. Something simple is fine.

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review. I updated the tooltips

**Comment by bwbaker1** [comment]
@wrynearson Looks good.
