### ISSUE TITLE
Users are able to bypass MFA setup by refreshing page

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#800]
### **Description**
Two separate users have noted having issues setting up MFA. The issue is that they did not understand the process of setting it up, however, they were able to bypass setting up MFA by clicking "refresh." Users should not be able to bypass setting this up, so we need to figure out the cause and fix it.

### **Acceptance Criteria**
- [x] Determine why users are able to bypass MFA when refreshing the page
- [x] Implement a fix to prevent this

cc @wrynearson

**Comment by wrynearson** [comment]
@frozenhelium, @thenav56, @sunu and @batpad – let's think of ways that we can enforce MFA without blocking/locking out users.

**Comment by sunu** [comment]
@wrynearson If the ask is to prevent users from bypassing the MFA setup process, we should make MFA mandatory instead of optional in the Cognito settings.

After setting up MFA, if someone is locked out, they should be able to contact someone with Cognito admin access to reset their MFA setup.

**Comment by wrynearson** [comment]
@sunu OK, I'll change this to mandatory. Someone with prod cognito access will have to change this setting on production as well.

<img width="1313" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/a0b2480d-1ae8-42c7-8312-cba1af4075fd">

Are there any implications to changing this that we can think of?

**Comment by sunu** [comment]
Apart from users being forced to set up MFA, I can't think of any

**Comment by wrynearson** [comment]
@bwbaker1 I just want to double check with you. If we make this field mandatory, then users will have to set up MFA the next time they access APT. They won't be able to do anything until they set up and log in.

You had mentioned that [some users are having issues](https://github.com/NASA-IMPACT/nasa-apt/issues/782) setting up MFA (because they don't have internet access on their cell phones in the building).

**Comment by sunu** [comment]
Just fyi, TOTP apps like Google Authenticator, Authy etc work fine without internet - both for settings up new 2FA accounts and generating 2FA codes for already set up accounts.

**Comment by wrynearson** [comment]
Yep, the issue was that users have to download MFA software 😆

**Comment by bwbaker1** [comment]
@wrynearson @sunu I think it is fine to make this mandatory. MFA is required by ESDS, so we need to ensure all users have it. I have prod cognito access, so I'm not concerned with having to reset MFA for someone that gets locked out. 

I think we somewhat resolved the issue with users not being able to download MFA software. I've had some conversations with others about this issue, and essentially it is out of our hands if someone can't download MFA. So this isn't a concern.

If this is just a matter of enabling "MFA is required" in cognito, let me know and I can do that. 

Thanks for checking into this!

**Comment by sunu** [comment]
@bwbaker1 yes, I think switching to "MFA required" from "MFA optional" in Cognito should do the trick.

**Comment by bwbaker1** [comment]
@wrynearson @sunu I ran into an issue with setting MFA as required. I created a new APT account for testing purposes, and was forced to enter a OTP upon my first sign-in, but was not given the MFA setup option (code or qr code). 

Looking through this [document](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa.html#user-pool-configuring-mfa), I found this:


![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/f4f589d4-e99b-4a10-b5d7-0b9577563ed7)

I don't want to do anything as I'm concerned I will do more damage than good in cognito.

**Comment by wrynearson** [comment]
@bwbaker1 this is ready on staging for you to test.
1. We tried creating multiple new users and never ran into the issue you described.
2. We think keeping the Cognito MFA setting as "optional" while making it required in APT (though frontend design/functionality) is a better approach, which we've gone ahead and done in this PR, for a few reasons:
    1. Setting the cognito user pool to `Required` means that users need to have an SMS-based backup if they want to reset their account. From what we understand, this isn't allowed by NASA policy
    2. If we keep the user pool to `Optional`, if a user needs us to reset their MFA, we can do that on an individual basis in the AWS console.

**Comment by wrynearson** [comment]
Sorry @bwbaker1 I got some of those details wrong. We'll actually keep the AWS Cognito pool as `required`. If we need to reset a user's account/MFA, we can change the pool to `optional` momentarily and then reset the individual user's account/MFA. We'll need to test this on staging.

**Comment by bwbaker1** [comment]
@wrynearson This is difficult for me to test because I don't have access to cognito for staging.

**Comment by wrynearson** [comment]
Oh right! I'll ping you when this is ready for production and we'll find a way for you to test it.

**Comment by bwbaker1** [comment]
@wrynearson I was able to test setting up MFA on staging without having my account approved through cognito. It worked as expected and I was unable to bypass setting it up. This is ready for prod.
