### ISSUE TITLE
Add tooltip for how to setup MFA

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#801]
### **Description**
Several users have reached out due to their not understanding how to set-up MFA. Several users thought that the provided code/QR to setup the authenticator app was the actual OTP (see image below). So they are inputting that code and getting an error. 

The [quick start](https://www.earthdata.nasa.gov/apt/user-guide/quickstart) guide shows the sign up process, but does not detail setting up MFA. Even if it did, I highly doubt many users are referring to the quick start guide (I do send a link to each user when I approve there account). 

The solution here is likely a tooltip that details the instructions on how to set it up and/or a quick video.

![Image](https://user-images.githubusercontent.com/56319064/262768307-cf859381-7dbe-4d93-98a2-540f3e107cfe.png)

### **Acceptance Criteria:**
- [x] Determine the best approach to providing instructions of setting up MFA (e.g., tooltip with instructions and/or video). Not sure which will be the easiest option.
- [x] Implement the chosen solution - ensure that the tooltip is accessible on production.

cc @wrynearson

**Comment by wrynearson** [comment]
@kamicut, could you add the following text as a tooltip, next to "Set-up OTP"?

> A one-time password (OTP) increases the security of your APT account. To use OTP with APT, you'll need to download an application (sometimes referred to as MFA) that generates a time-sensitive code (OTP) that is entered upon login. APT doesn't endorse any particular application, but some include [Google Authenticator](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en&gl=US) (Android, iOS), [Microsoft Authenticator](https://www.microsoft.com/en/security/mobile-authenticator-app) (Android, iOS), and [1Password](https://1password.com/) (Android, iOS, Mac, PC, Linux, web browser). Please follow the respective application's instructions for how to install and setup the OTP generator.

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review on staging

**Comment by bwbaker1** [comment]
@wrynearson This is good. I think this is much more clear for users. Ready for production.
