### ISSUE TITLE
Not all users have content for Mathematical Theory/Assumptions section (update UI text)

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#802]
### **Description**
Several users have noted that they do not necessarily have distinguishable content for the Scientific Theory and Mathematical Theory sections. Therefore, they are requesting that this section either be hidden (see screenshot below). The other option would be to provide some informative placeholder text. However, this will likely not be appealing on published documents. 

![Image](https://user-images.githubusercontent.com/56319064/262772461-9fc3d3b3-6d84-49ab-b229-b8038396bf2c.png)

### **Acceptance Criteria:**
- [x] Scope out the options
- [x] Determine the best option in both terms of simplicity to implement but also user satisfaction.
        • We decided the best option is to require users to add some text within this section/subsection. They can provide a couple of sentence summary of this and also note to see "Scientific Theory" section above. 
- [ ] Deliver to DevSeed - update UI text prompt to reflect what is needed if they don't have any content here

NOTE: A main point of APT is to standardize content, so removing/adjusting the standardization for users is not ideal. However, the standardized ATBD template has not been tested with users. So this is something to consider since we are getting feedback from multiple users/teams regarding some of our standardization.

**Comment by bwbaker1** [comment]
@wrynearson I'm interested in your thoughts after you have had some time to think about this issue/challenge. I will be seeking feedback from others on the IMPACT side as well.

**Comment by wrynearson** [comment]
@frozenhelium could you share how difficult it would be to:
1. Modify/remove sections
2. Hide sections (@bwbaker1 only for certain users?)
3. Make more sections optional (@bwbaker1 is that an option?)
4. Add placeholder text to optional text fields

**Comment by bwbaker1** [comment]
@wrynearson 
2. It would be to hide sections for users that don't provide content. 
3. I think making certain sections optional would be good. However, it would only be specific sections.

**Comment by wrynearson** [comment]
Ah OK, thanks @bwbaker1. Is the following process that's being requested correct?
1. Users see the same `edit` mode
2. We treat `Mathematical Theory/Assumptions` as an optional section
3. If a user doesn't provide content in `Mathematical Theory/Assumptions`, then we hide the heading and the content in the view and PDF modes (document and journal).

**Comment by bwbaker1** [comment]
@wrynearson ⬆️ Yes, this is ideal.

**Comment by wrynearson** [comment]
@frozenhelium let us know if there are any issues with ☝️

**Comment by wrynearson** [comment]
Sorry @bwbaker1, I didn't fully spec this ticket out. None of the APT sections (if I'm not mistaken) are "mandatory". Instead, if a section doesn't have content, we have a placeholder in the `view` and `document PDF`, and the section is not rendered in the `journal PDF`.

Would another approach be to let users know (in the UI or when they reach out to you) that no section is required? I agree that the more we change individual sections for individual use cases, the more we go away from our vision of having a standardized report structure. However, if it becomes evident that we need to change the format for _all_ users, we can explore that.

**Comment by bwbaker1** [comment]
@wrynearson I updated this ticket a few weeks back (acceptance criteria). We decided the best route is to require users to add some content in all of these sections, even if it is just 1-2 sentences within the mathematical theory sections thats says "see the scientific theory section above for an explanation on the mathematical theory." 

I would like to update the text prompts for the mathematical theory and mathematical assumptions to the following:
1. Describe the mathematical theory: "Provide a description of the mathematical theory essential to algorithm development. If this is described in the scientific theory section, summarize it in this section in a couple of sentences." 
2. Mathematical theory assumptions: "Provide a description of any mathematical assumptions, simplifications and approximations made when deriving the algorithm. If this is described in the scientific theory section, summarize it in this section in a couple of sentences."

**Comment by wrynearson** [comment]
OK sounds good @bwbaker1. @vgeorge, if you have time to get to this before tomorrow afternoon, please update the text prompts as described above ☝️

**Comment by wrynearson** [comment]
nvm @vgeorge, I pushed a PR: https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/552

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson Looks good.
