### ISSUE TITLE
Add Google Analytics to APT

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt#807]
_Related ticket: https://github.com/NASA-IMPACT/nasa-apt/issues/791_

As APT enters maintenance mode for FY24, gathering APT usage statistics will be important for understanding how the tool is used and to what capacity.

Core pieces of information needed are:

- [x] The number of template -> PDF upload users
- [x] The number of APT editor users
- [x] The number of active users

Google Analytics, in use on other IMPACT projects, is a good candidate. We can start with basic functionality, and then expand to fit our future needs.

**_Note: APT metrics using Google Analytics was discussed a few years back ([here are the notes](https://docs.google.com/document/d/1-DWC6z0-yAuFuBfNeAG8hCcgN8E7gwptl5j-nk24MYk/edit#heading=h.6jwqchbkfibp)). Of course, this will need to be reviewed/updated, but it is a start._** 

## Acceptance Criteria

- [x] Google Analytics is set up for APT on production
- [x] The above core pieces of analytics are captured ☝

**Comment by wrynearson** [comment]
@bwbaker1 (or @xhagrg) could you give us IMPACT's Google Analytics tracker code (it might look like `UA-XXX`)?

**Comment by bwbaker1** [comment]
@wrynearson The tracker code for APT Production is UA-163103126-2

**Comment by wrynearson** [comment]
Thanks @bwbaker1! @frozenhelium, is this something you could look into, or should DevSeed lead this once we're back?

**Comment by wrynearson** [comment]
https://github.com/NASA-IMPACT/nasa-apt/issues/798#issuecomment-1693383069

Related issue, but good context for the information we should be gathering, if possible👆

**Comment by wrynearson** [comment]
@sunu will look into this

**Comment by bwbaker1** [comment]
@wrynearson @sunu I think just the main metrics noted in the description are fine. We don't need to go overboard with this.

**Comment by sunu** [comment]
This might be more involved than we thought it would be. Google Analytics has recently [moved from "Universal Analytics" to "Google Analytics 4"](https://support.google.com/analytics/answer/13467533?hl=en#zippy=%2Cin-this-article). As a result, the [react-ga library](https://github.com/react-ga/react-ga) we use is no longer supported.

However, there is a new library called [react-ga4](https://www.npmjs.com/package/react-ga4) which seems like a drop in replacement. We can try to integrate that into our codebase.

Update: looks like `react-ga4` is not a drop in replacement. It's missing some of the helper functions that `react-ga` had.

**Comment by wrynearson** [comment]
@bwbaker1 unfortunately this needed additional work due to the change to Google Analytics 4. Most of the pieces are in place, but we need to update some frontend code to get the functionality we're hoping for.

**Comment by wrynearson** [comment]
@bwbaker1 we have good initial functionality to track usage of APT, based on https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/563. I'd suggest we move forward to set this up on production and with IMPACT's Google Analytics account.

Here's a video of some of the analytics:

https://github.com/NASA-IMPACT/nasa-apt/assets/25919630/5691eb74-1e2f-4b3e-bd47-5c54fb591f7f

What we don't have is a way to track explicitly which PDF uploads use template, but we do have the number of templates (and their type) that are downloaded. Explicitly tracking the usage of templates on PDF uploads would require some frontend and backend changes, so I'd suggest we put that in the backlog unless it's an absolute requirement.

**Comment by bwbaker1** [comment]
@wrynearson This looks! Go ahead and push to production. Our feedback form for completed ATBDs specifically asks which template they ultimately used. This just relies on users to fill out the form. The biggest question is how many people are working on templates vs the UI. Of course, the number of downloads can be misleading. However, I send an email when I approve an account, so I can just request that they let me know if they are using a template. I'm not sure of another way to track this since they can always change their mind later.

**Comment by wrynearson** [comment]
OK sounds good @bwbaker1. We have another way in mind (adding a radio select button in the `upload` step of PDFs) to track the type, but this will be a medium-high LOE (because we'll have to make some database changes), so I don't think we should do that immediately. Let's go with the form, plus the Google Analytics functionality, and see if that meets your needs.
