### ISSUE TITLE
APT generated citations not formatted correctly

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#825]
### Description
The current format of generated ATBD citations changed at some point and is no longer correct. 

Current example from UI: 

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/3ec80830-05b0-4233-94fc-09826800c5dc)

It should look like the following: 
Hu, C., Werdell, J., O'Reilly, J., Feng, L., Lee, Z., Franz, B., Bailey, S., & Proctor, C. (Publication Date). Chlorophyll a, v1.0. NASA Algorithm Publication Tool. (DOI).

Format:
lastname, first initial., lastname, first initial., ..... & lastname, first initial. (Publication Date). Title, Version. Publisher.  Online Resource. DOI. 

The citation link is also incorrect. It is missing "apt/"

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/c3f97e85-d7f2-490e-afc4-c67b4bbba065)

**Comment by bwbaker1** [comment]
@ashleyriddle92 Will you review this format and verify it is correct?

**Comment by ashleyriddle92** [comment]
If were to use a journal format, it would look like this:

Hu, C., Werdell, J., O'Reilly, J., Feng, L., Lee, Z., Franz, B., Bailey, S., & Proctor, C. (Publication Date). Chlorophyll a, v1.0. _NASA Algorithm Publication Tool_. (DOI).

**Comment by kamicut** [comment]
Hello @bwbaker1 if the document has an existing DOI (as input in the identifying information), should we use the existing DOI or the generated URL pointing to the document?

**Comment by bwbaker1** [comment]
@kamicut We should use the existing DOI.

**Comment by wrynearson** [comment]
@bwbaker1 this is on staging and ready for your review

**Comment by bwbaker1** [comment]
@wrynearson There are a few issues. This is what I get.

![Screenshot 2024-03-27 at 10 28 33 AM](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/49ab71ca-d4a8-452f-a01a-758561f9b03b)

It should look like this:
Baker, B. & Riddle A. (publication date). APT Citation Generator Test, v1. _NASA Algorithm Publication Tool_. (DOI)

So only the first name initial should be displayed and the publisher should be italicized.

**Comment by kamicut** [comment]
1. @bwbaker1 could you check that you've entered the name of the editors in the format `Lastname, Firstname` in the Identifying information section? We are standardizing those inputs across the application so that we can correctly identify the last name(s)
2. I will look into italicizing the publisher.

**Comment by wrynearson** [comment]
@bwbaker1 are these the screenshots you meant to include? The citation is being driven by the citations form in the 1st step of the edit flow (Identifying Information), not the contacts form in the 2nd step

**Comment by bwbaker1** [comment]
@wrynearson Sorry. but I guess I didn't preview those for commenting. It should have been these.

![Screenshot 2024-03-28 at 7 53 46 AM](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/3d6d34f1-97b5-494e-ba9b-611d25e962d3)


![Screenshot 2024-03-28 at 7 54 08 AM](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/1560e179-175c-414c-8307-7d9ff665a6e0)

The final citation should be the following:

Baker, B. & Riddle, A. (publication date - null). APT Citation Generator Test, v1. _NASA Algorithm Publication Tool_. (10.1029/2022EA002516).

**Comment by wrynearson** [comment]
We're working on the first names not appearing. We should have a fix this week.

For the italics, it looks like it will require more changes. How critical is this issue? Could users who are copying the citation apply formatting changes elsewhere for the time being?

> (publication date - null)

If there is no publication date, should we explicitly say "publication date - null", or is "null" enough?

**Comment by bwbaker1** [comment]
@wrynearson This isn't a high priority right now. It looks better than it did before.  The bigger issue is [#843](https://github.com/NASA-IMPACT/nasa-apt/issues/843) because we have someone ready to publish but can't until the order of the contacts is correct. Also, another document is in review, so that is going to lead to the same issue soon.
