### ISSUE TITLE
Reference section citations have extra commas

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#827]
### Description
It was noticed that in the list of authors, there are unnecessary commas following author initials. If an author provides two initials, only the last initial should have a comma.

Current example from APT

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/7ceb30c4-3836-447e-b621-09f95c274f62)

There should not be a. comma following the author's first initial. For this example, the authors should look like this:
Gordon, H.R., Clark, D.K., Mueller, J.L., & W.A.H. (1980). etc. 

### Acceptance Criteria
- when two author initials are provided, only the second initial has a comma (both initials have a period though)

**Comment by wrynearson** [comment]
@bwbaker1, can you link to the document that this is happening in?

**Comment by bwbaker1** [comment]
@wrynearson Here is one example: https://www.earthdata.nasa.gov/apt/documents/journal-pdf-testing/v1.0#doc-header

**Comment by kamicut** [comment]
Hey @bwbaker1 I don't have access to this document. Is there a document in staging that has this behavior? I'd like to figure out what could be causing this to replicate it locally.

**Comment by bwbaker1** [comment]
@kamicut I added you to this[ doc ](https://nasa-apt.surge.sh/documents/reference-test/v1.0#doc-header)on staging. It shows the behavior of adding commas after each author's initials. 

Here is the AGU reference style guide: https://libguides.humboldt.edu/ocn/agu

**Comment by wrynearson** [comment]
@bwbaker1 @kamicut I tested this on https://nasa-apt.surge.sh/documents/wills-test-atbd/v1.0 and can confirm that this is an issue for the _reference section_, but isn't an issue for the _inline citations_. The functionality is different that what we are communicating to users.

1. With the `authors` field filled in with `Author, Test and Another Author, Testing`, the resulting reference is `Author, T. & Another Author, T. Title.`. **This is correct**.
2. With the `authors` field filled in with `Test, This is a and Another Test, Why not another`, the resulting reference is `Test, T.,I.,A. & Another Test, W.,N.,A. Title 2.`. **This is incorrect**. It should be `Test, T.I.A. & Another Test, W.N.A. Title 2.`

Logic to use:
1. The word `and` separates last name(s) with first name(s)
2. Anything that comes before the `and` should be treated as the last name(s) and should be displayed in the way that users input the text. _This is the user's responsibility_
3. Any series of letters _after_ the `and` should be treated as the first name(s). 
    1. If there are no spaces (e.g., `and Hello`), the resulting first name should just have the initial of the first name (e.g., `, H.`)
    2. Each space after the `and` separates each first name (e.g., `and Hello There` should be rendered as `, H.T.`)

**Comment by bwbaker1** [comment]
@wrynearson This looks good. It's ready for PROD.

**Comment by bwbaker1** [comment]
@wrynearson Can we close this ticket?

**Comment by bwbaker1** [comment]
@wrynearson Re-opening because it didn't get pushed to production. Sorry, I just realized it. We can add this when we push #784 to production.
