### ISSUE TITLE
Add link to NASA accessibility statement to the footer of all web pages

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#844]
### Description:
MCP requires all NASA websites have a link in the footer to NASA's accessibility statement. 

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/8d10f904-7cc0-417e-b01d-aa7239b7d1f9)

### Acceptance Criteria:
- [ ] link is located in the footer of each page (https://www.nasa.gov/accessibility/)

**Comment by bwbaker1** [comment]
@wrynearson FYI, Chris P. sent this to me. Apparently this is required.

**Comment by wrynearson** [comment]
OK, we have a fix up on staging

**Comment by bwbaker1** [comment]
@wrynearson Looks good!
