### ISSUE TITLE
Add table, figure, and equation number into edit mode

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#858]
### Description
Table, figure, and equation numbers only display on the PDFs and not in edit or HTML view. This is confusing for users when they are referencing these while writing. For example, they may have 15 equations that they are referencing in text.

### Acceptance Criteria:
- Review solution to add table, figure,  and equation numbers to edit and html mode (edit mode is the priority)
- Implement the solution
- Test

**Comment by wrynearson** [comment]
Hi @bwbaker1, could you explain a bit more what you mean by "referencing these while writing"? Is this confusing for an individual author who might want to remember which table/figure/equation is which, or for collaborative documents where multiple authors/reviewers are trying to ask about a table/figure/equation?

**Comment by bwbaker1** [comment]
@wrynearson This is for an individual writing a document. For example, one TEMPO ATBD has 16 figures, 5 tables, and 8 equations and throughout the document, they are referring back to these. It is confusing, time-consuming, and frustrating to have to determine which "number" needs referencing. They have three options: (1) go back and count which figure they want to ref, (2) switch to view mode to see the number, or (3) manually add it into the text and go back and delete it when the document is complete. TEMPO is doing option 3, but they are frustrated with having to do that and said it is a deal breaker for them. This issue will be raised by others as well.

I completely understand their frustration. I think this was overlooked by the IMPACT team early on in development.

**Comment by wrynearson** [comment]
That makes sense, thanks @bwbaker1. We'll look into it and estimate the complexity of adding this as a feature. 

cc @frozenhelium @vgeorge

**Comment by wrynearson** [comment]
Hi @bwbaker1, we estimate this to take around 1 sprint to do, so it's definitely possible to do in any of the upcoming quarters.

There may be mismatches between the edit, view and PDFs with respect to the order of where content appears. What should the "source of truth" be?

1. The order in which users add them (edit-priority)
2. The order in which users read them (view-priority)
3. The order in which users read them (document pdf-priority)
4. The order in which users read them (journal pdf-priority)

It would probably make more sense to do a read-priority (options 2-4) but this may be confusing for authors and reviewers/editors.

We'll look more in depth this week as one of our team members has some capacity to do so, but we'll schedule the work later in FY24Q4.

**Comment by wrynearson** [comment]
@bwbaker1 are you no longer requesting this feature? I'd be curious to know why not...
