### ISSUE TITLE
Address MCP tickets

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#870]
![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/4f14202a-01b3-4fa0-9bbb-222c4e7ae37e)

**Comment by bwbaker1** [comment]
@wrynearson FYI, Chris P. shared a few APT MCP tickets. Will you keep me updated on the progress of these so that I can keep our cloud mgmt team in the loop? I meant to tag you on this ticket a few weeks ago.

**Comment by wrynearson** [comment]
Will do @bwbaker1.

@sunu and possibly @leothomas / @jjfrench, could you help me give Brad updates?

**Comment by sunu** [comment]
@wrynearson This probably requires MCP access.

@leothomas / @jjfrench - would you have time to take a look? If some of these changes are better done through CDK, we can ticket that out separately to address individually.
