### ISSUE TITLE
Bug: figure/table captions do not work correctly with special characters

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#878]
### Description
Table and figure captions do not display correctly on a PDF when the caption includes special characters. The caption is cutoff once a special character is used.

**Figure example:**
_Edit mode_

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/96415c21-61fa-4708-aa9a-2baf5cd8a660)

_View mode_

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/88467e01-84c9-4d3d-b635-29dbf46bd228)

_PDF view_

![Image](https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/01665d6c-f4a8-488a-8a3e-b0d0da4b9022)

**Comment by bwbaker1** [comment]
@wrynearson A user brought this to my attention today. It is someone that is actively working on several ATBDs.

**Comment by wrynearson** [comment]
Hi @bwbaker1, I wasn't able to reproduce this. I tested with [this document](https://nasa-apt.surge.sh/documents/testing-the-journal-pdf-output-w/v1.0) and added a bunch of "special characters" (like ©, ® and 😀, 🌍, 🎉, 👋 and ₂ ²) to the 2nd image caption in the "Additional Information" [subsection](https://nasa-apt.surge.sh/documents/testing-the-journal-pdf-output-w/v1.0#additional_information). 

They all rendered correctly in the PDF preview and exported PDF. 

Did you see this issue in more than this document? Which document was it in?

**Comment by bwbaker1** [comment]
@wrynearson Interesting. I created a new document and still had the issue. I did an end-to-end screen recording so you can see exactly what I am doing.

https://github.com/NASA-IMPACT/nasa-apt/assets/56319064/948b8a97-2085-4482-acc2-b8f5b0246fbf

**Comment by wrynearson** [comment]
Thank you so much for the screen recording! They're super helpful for debugging issues.

I see that you used the rich text editor and that everything after the bolded text was cut out. That's different than how I tested it (adding non-ASCII characters that I copied in from elsewhere). Using your method, I'm able to reproduce the issue.

@batpad @kamicut @vgeorge – any ideas as to what's happening?

**Comment by wrynearson** [comment]
@bwbaker1 this is fixed, but we're having issues deploying it to staging.

**Comment by bwbaker1** [comment]
@wrynearson Ok, just let me know when it is ready for testing.

**Comment by bwbaker1** [comment]
@wrynearson This works now. It is ready for production.
