### ISSUE TITLE
Document and Journal PDF formatting discrepancies

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt#883]
### Description
Following a thorough review of the external ATBD templates for ESCO review, a few formatting issues were identified. 

This [document](https://docs.google.com/document/d/1uKzsl9ogHIV0vLSrI2nAzlWhqoTq0R5Y1Tkh5mi_oKY/edit) details the needed fixes.

### Acceptance Criteria
- [x] Document PDF ATBD title is centered on title page
- [x] Document PDF sections 3.1.1 and 3.2.1 is renamed
- [x] Document PDF section 6 "Performance Assessment Validation Uncertainties" renamed 
- [x] Document PDF sections 6.1, 6.2, and 6.3 renamed
- [x] Document PDF section 7 "Data Access" renamed
- [x] Document PDF sections 7.1 and 7.2 renamed
- [x] Document PDF "Contacts" section renamed
- [x] Journal PDF author affiliations centered on title page
- [ ] Journal PDF Reference section is not numbered

**Comment by bwbaker1** [comment]
@wrynearson I recently noticed these inconsistencies between the journal and document PDF while preparing for the ESDIS Standards Coordination Office review (external templates).

**Comment by wrynearson** [comment]
Thanks, I requested access to the document.

**Comment by wrynearson** [comment]
@bwbaker1 I think you linked the wrong document

**Comment by wrynearson** [comment]
Also, can all of the content renaming items be based on the view mode? Changing the view mode content and then adding it to the journal and document PDFs will be significantly easier.

**Comment by bwbaker1** [comment]
@wrynearson Sorry, I updated the link.

I think it will be fine to rename content based on the view mode.
